### ISSUE TITLE
Optionally pass accessToken as a parameter to returnTo

### ISSUE THREAD

**Issue by gausie** [strongloop/loopback-component-passport#102]
On mobile devices, it is useful to have the login redirect to a URL with a custom protocol (myapp://) so that the intent can be captured and the login processed. In 1.6.0 we have the ability to set a returnTo session key for the successRedirect. 

It would be extremely useful to be able to append the accessToken generated from a successful login to this URL as query parameters, as they can be read by a mobile application.

**Comment by jonathan-casarrubias** [comment]
when you configure the passport provider you set the success url, set that as a middleware in the backend like

````javascript
"successRedirect": "/auth/account"
````

then just create a middleware like

````javascript
app.get('/auth/account', function (req, res, next) {
        app.models.Account.findOne({
            where: { id: req.accessToken.userId },
            include: 'channel'
        }, function(err, account) {
            if (err) { next(err); }
            res.redirect('http://yourdomain.com?accessToken=' + req.accessToken.id + '&userId=' + account.id);
        });
    });
````

**Comment by anupvarghese** [comment]
Thanks @jonathan-casarrubias this is a good suggestion.

This looks like a good option for SPA login. I am using it as below in my react client app,
`Login.jsx`
```
import React from 'react';
class Login extends React.Component {
render() {
    const googleLogin = () => {
      window.open('http://localhost:3000/auth/google'); // Do some modifications for window close on successful login or cancel clicks
  };
}
return (
  <div>
    ........
    <a href="#" onClick={googleLogin}>Google +</a>
  <div>
  );
}
```

at `server.js` in loopback app

```
app.get('/auth/account', function(req, res, next) {
  console.log(req.accessToken);
  //res.json(req.accessToken);
  res.redirect(301,'http://localhost:8080/dashboard?accessToken=' + req.accessToken.id);
});
```
Is it possible to create a middleware in the failure case also?
