### ISSUE TITLE
Create fails on non standard user model

### ISSUE THREAD

**Issue by mbouclas** [strongloop/loopback-component-passport#106]
I have a user model with some added properties that are required. When i do FB auth for example, everything goes as planned up to the point where the new user needs to be created. Validation fails of course since my fields are missing. How can i setup what happens after the FB login is completed? 
In passport you do something like new FacebookStrategy(strategy, loginFacebook) where the 2nd parameter is your callback where you check if the user exists and add your custom logic. 

How can i set my custom fields with default values before the create is fired?

**Comment by jonathan-casarrubias** [comment]
https://github.com/strongloop/loopback-component-passport/issues/95

**Comment by superkhau** [comment]
Duplicate, closing.
