### ISSUE TITLE
Security vulnerability in loopback-passport-component

### ISSUE THREAD

**Issue by jamesjjk** [strongloop/loopback-component-passport#107]
edit by @rmg: **discussion moved to email**

**Comment by superkhau** [comment]
@loay ^

**Comment by loay** [comment]
@jamesjjk @superkhau Thanks .. will have a look shortly.

**Comment by superkhau** [comment]
@jamesjjk FYI, next time please inquire about vulnerabilities via callback@strongloop.com instead of the public channels.

@loay Can you create a section in the [LoopBack Wiki](https://github.com/strongloop/loopback/wiki) regarding this? Just so community users know what to in situations like this.

**Comment by jamesjjk** [comment]
@superkhau No problem will contact you via callback@strongloop.com

**Comment by loay** [comment]
@superkhau Security page is up.

**Comment by superkhau** [comment]
@loay @rmg TY.
