### ISSUE TITLE
user-identity.js findOrCreate always fails  (memory connector, perhaps others)

### ISSUE THREAD

**Issue by mediapolis** [strongloop/loopback-component-passport#123]
For the use case:
  user creates native account with email & password
  user later comes back and logs in with facebook instead
  passport matches email in facebook identity to email in user table using findOrCreate on user table

Unfortunately the email property in the user table has a "unique" validation and datasource-juggler findOrCreate validates the data object before doing the find (or create) throwing an error because the email exists in the user table... This seems like odd behavior which has generated some discussion but no action:

https://github.com/strongloop/loopback-datasource-juggler/issues/529 

The quick fix for me was to change in user-identity.js: 
  userModel.findOrCreate({where: query}, userObj, function (err, user)...
to:
  userModel.findOrCreate({where: query}, userObj, { validate: false }, function (err, user)...

This is sub optimal as we could possibly insert an invalid data object once the find fails.

I think this is really a problem with datasource-juggler but wanted to bring it to the attention of this repository as this affects a common use case for passport.

**Comment by jannyHou** [comment]
@mediapolis thanks for your workaround!
I am trying to debug what's going wrong here but still confused how to reproduce it, I don't quite understand this description "passport matches email in facebook identity to email in user table using findOrCreate on user table"..
Could you explain the steps to reproduce your problem?

**Comment by jeisinge** [comment]
I too am having baffling results with `User.findOrCreate()`.  In particular, it appears that the function _always_ attempts to create a new user.

My code is based off of https://github.com/strongloop/loopback-example-passport , I have added `server/boot/find-or-create-user.js` with the following:

```
module.exports = function(app) {
	var Promise = require("bluebird");
	var User = app.models.User;
	
	var userToCreate = {
			email : 'foo@bar.com',
			password : 'bar'
		};

	var byUsernameOrEmail = { where: { or : [ { username : 'foo_user' }, { email : 'foo@bar.com' } ] } };
	
	Promise.delay(1000)
		.then(() => User.findOne(byUsernameOrEmail))
		.delay(1000)
		.then((user) => console.log("User should NOT exist yet: ", user))
		.delay(1000)
		.then(() => User.create(userToCreate))
		.delay(1000)
		.then((user) => console.log("User created: ", user))
		.delay(1000)
		.then(() => app.models.user.findOne(byUsernameOrEmail))
		.delay(1000)
		.then((user) => console.log("User SHOULD exist yet now: ", user))
		.delay(1000)
		.then(() => app.models.user.findOrCreate(byUsernameOrEmail, userToCreate))
		.delay(1000)
		.then((user, created) => console.log("User should not be created and should be found: ", user, created))
		.delay(1000)
		.catch(err => console.log("Error caught: ", err))
		.delay(1000);
}
```

It's failing.  I am relatively new to Node.js and definitely new to LoopBack, so my syntax and/or logic might be off.  Any help is much appreciated!

# Use Case / Background
Our use case is to link two accounts on first login of either account.  It appears that this is possible through providing `options.profileToUser`.  However, the `UserIdentity.login` function calls `User.findOrCreate` which always attempts to create the new user.
