### ISSUE TITLE
No need to hack profileURL in passport-facebook

### ISSUE THREAD

**Issue by fuffenz** [strongloop/loopback-component-passport#124]
The readme suggest that we need to change the profileURL in passport-facebook, but that isn't necessary.  Just add the appropriate profile fields in your providers.json file and passport will make sure you get the fields you need.

``` javascript
{
    "facebook-token": {
        "provider": "facebook-token",
        "module": "passport-facebook-token",
        "strategy": "FacebookTokenStrategy",
        "clientID": "xxx",
        "clientSecret": "xxx",
        "callbackURL": "...",
        "profileFields": [ "id", "email", "gender", "link", "locale", 
                            "name", "timezone", "updated_time", "verified"]
      }
}

```

(example for passport-facebook-token, but same goes for passport-facebook)

**Comment by sebastianhaas** [comment]
:+1:

**Comment by jannyHou** [comment]
@fuffenz @sebastianhaas thanks for your suggestion!
some users also mentioned this before, I will update the alternative way in doc.
