### ISSUE TITLE
SAML 2 support

### ISSUE THREAD

**Issue by athakral** [strongloop/loopback-component-passport#126]
We need to support wsfed-saml2 authentication in our project. 

I can try to add this 

https://github.com/auth0/passport-wsfed-saml2 

and make changes to support saml2. But would need some guidance from the team :). 

Let me know what you guys think.

Regards
Aman

**Comment by mkaag** [comment]
+1

**Comment by jannyHou** [comment]
@athakral @mkaag I am trying to help but to be honest I never try to conbine loopback with another passport.... 
This example https://github.com/strongloop/loopback-example-passport explains how the loopback-component-passport works in a very detailed way, hope it could provide you some clues.

**Comment by jannyHou** [comment]
I am labelling this issue a feature to either add a doc explaining how to extend component-passport with custom auth, or if we are not extendable enough, to implement some apis to make it easy to work with custom authes.
