### ISSUE TITLE
is this repository slowly dying?

### ISSUE THREAD

**Issue by julien-sarazin** [strongloop/loopback-component-passport#128]
There are 16 pull requests, ATM the most recent is from January 12th. 
No update since a long time.

Is this repository still maintained by the strongloop team? Do we need to focus on another component or develop our own?

Thanks.

**Comment by superkhau** [comment]
@julien-sarazin No, we've just all been busy on various projects. Things will be back to normal nexet week. We will also be implementing new procedures to triage PRs like we do for bugs/features. I will formalize it in the LoopBack wiki in the coming weeks.

**Comment by julien-sarazin** [comment]
@superkhau Glad to read that. Thanks for the reply.
