### ISSUE TITLE
Missing documention for "json": true option

### ISSUE THREAD

**Issue by phra** [strongloop/loopback-component-passport#130]
hi,

we are porting a webapp to android & ios via cordova and we have to set property "json": true on the provider to have a working social login. (switch from http redirect mode to json)

why can't we find this property on the documentation? it's a docs bug or it will be deprecated?

thanks.

**Comment by phra** [comment]
seen json: true on this ticket -> https://github.com/strongloop/loopback-component-passport/issues/83

**Comment by jannyHou** [comment]
@phra thanks for you suggestion and the effort you and other users spent to get this work on android&ios.
If I understand correctly, a normal provider config like:
 ```
"facebook-login": {
    "provider": "facebook",
    ...
    // OTHER SETTINGS
  },
```
would not work for android&ios but 
```
"facebook-login": {
    "provider": "facebook",
    "json": true
    ...
    // OTHER SETTINGS
  },
```
would right?

As you could see from https://github.com/strongloop/loopback-component-passport/issues/83, login on those two platform is still in discussion. It's more like a feature that still in build. 
So 
>  or it will be deprecated
I don't think it will be deprecated.
We will well documented it after we finish the feature.
So I will keep this issue as a doc issue, which will be take care of when features are done:)

**Comment by phra** [comment]
thanks for your time.

yep, it's right.
