### ISSUE TITLE
No composite id for externalId and provider

### ISSUE THREAD

**Issue by ernie58** [strongloop/loopback-component-passport#131]
I noticed one can insert a UserIdentity with externalId and provider combination that exists already in the database. I think a validation rule or composite ID is needed here.

I know, with the existing flow used in this component, duplicates are handled elsewhere, so in practice this can never happen.

However, I'm writing some hooks to keep UserIdentities and UserCredentials in sync (one to one), so when a user links a third-party, in the after save hook for a UserCredential, I create a UserIdentity if it doesn't exist already.

That's when I stumbled upon this case.
See also https://github.com/strongloop/loopback-component-passport/issues/19

**Comment by superkhau** [comment]
Can you provide a sample for us to reproduce the issue? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report
