### ISSUE TITLE
How to make passport aware of the current user after successful User.login() ?

### ISSUE THREAD

**Issue by luxigo** [strongloop/loopback-component-passport#134]
Hello !

I am using the loopback-sdk-angular and I defined a "signin" remote method for the "user" model.

After following the steps described in this document:
https://docs.strongloop.com/pages/releaseview.action?pageId=3836277#Third-partylogin(Passport)-Overview

I can login with local accounts and third-party accounts, but I am only able to link third-party accounts to other third-party accounts...

I found it was because req.user is undefined at
https://github.com/strongloop/loopback-component-passport/blob/e38446687312992b8e16aa7cb115bb974230bad6/lib/passport-configurator.js#L337

However after local login with user.login() (without using passport-local) I only have the current userId available here as "req.signedCookies.userId" when trying to link a third-party account.

A possible workaround is to add something like this to server.js:

```
app.use(function setCurrentUser(req, res, next) {
  if (req.accessToken) {
     app.models.user.findById(req.accessToken.userId, function(err, user) {
        if (!err) {
           req.user=user;
```

Maybe it's preferable to set "req.session.passport.user" after successfull user.login() but the 'user' property doesn't seems to be a valid userId.

What is the proper way to make passport aware of the current user after successful user.login() ?

**Comment by zallek** [comment]
:+1:

**Comment by superkhau** [comment]
Would you guys like to submit a PR with a test case to reproduce your issue?

**Comment by ntrinquier** [comment]
I confirm that in my case, adding the middleware
```javascript
(req, res, next) => {
  if (req.accessToken) {
    app.models.User.findById(req.accessToken.userId, (err, user) => {
      if (!err) {
        req.user = user;
      }
    });
  }
  next()
}
```
solved the problem.
