### ISSUE TITLE
why @loopback.provider.com

### ISSUE THREAD

**Issue by sanandrea** [strongloop/loopback-component-passport#135]
I am new to this plugin and social logins server side in general. Why is email appended by `@loopback` instead of setting correct email received from auth callback?

**Comment by loay** [comment]
Hi @sanandrea 
There were few reasons that include some security, as well as in certain cases, the 3rd party account could hijack the local account if the email is similar. 
The read file explained how to obtain the facebook email from the user. 
Also, google+ provides the email within the credentials of the account. 
Twitter does not provide the email when logging as a third party account. 
Please let me know if you have a further question concerning that issue. 
Thanks.

**Comment by sanandrea** [comment]
@loay Thanks for your response! I saw how to obtain the email from facebook and gmail. I was just wondering about the choice and did not want to go in the opposite direction by 'hard coding' the original email in `user-identity.js`. Thanks again

**Comment by loay** [comment]
@sanandrea You are welcome.
Actually, it is easy to hardcode now. You have the option of generated email and profile email. You can simply modify it by changing couple of words. 
Thanks

**Comment by jannyHou** [comment]
Thank you Loay, I am closing it since the question is solved. Please feel free to reopen it if anyone has further questions:)
