### ISSUE TITLE
Let passportConfigurator.configureProvider return the created Strategy

### ISSUE THREAD

**Issue by ernie58** [strongloop/loopback-component-passport#137]
Now `passportConfigurator.configureProvider ` returns nothing.
It would be handy if it returned the new Strategy it just configured.

In my loopback app, I want to update a users facebook profile .
I'd like to reuse the `FacebookStrategy.prototype.userProfile` for that, to get the same structure, that I've saved in the UserCredential table

Seems the only way I can reach that function is via:
`app.passport._strategies['facebook-login'].userProfile``
which I don't like because of the _strategies private intention

I'd be happy to make a pull request for this

**Comment by superkhau** [comment]
>I'd be happy to make a pull request for this

Please do. :+1:

**Comment by ernie58** [comment]
@superkhau PTAL thx!

**Comment by superkhau** [comment]
Can you link to the PR?
