### ISSUE TITLE
Security concern for matching by e-mail/username

### ISSUE THREAD

**Issue by ernie58** [strongloop/loopback-component-passport#139]
I have  a main platform in which I let users login with Facebook or SomeOtherService (with SSO  oAuth 2.0). 

Suppose:

1. User A has a facebook profile with e-mail example@gmail.com
2. User A creates his account on the main platform, via Facebook SSO
3. User B has a profile on SomeOtherService, and sets his e-mail to example@gmail.com (no verification needed)
4. User B logs in with SomeOtherService

Result: User B now logs into User A his main platform account, because the identical e-mails get matched. 

I know this is the intended behavior, but it could be a way to hack a profile on the main platform

[see UserIdentity.login()](https://github.com/strongloop/loopback-component-passport/blob/master/lib/models/user-identity.js#L124-158)

Is there a way to work around this issue?
I could omit the e-mail in the profileToUser function, but that would save the new user without e-mail.

**Comment by Overdrivr** [comment]
According to the README, the email address used for the User model is following this template `user_id_on_provider_plaftorm@loopback.provider.com`. And also, it seems the password for each email is randomly generated, user A or B are not aware of it. So I don't think having two different users with same email will cause an issue here.

**Comment by ernie58** [comment]
I see. I use custom profileToUser functions to match the third-party data to a loopback user.
In those I set the e-mail of the user to the third party main e-mail if provided. 
Guess I should not do that.

OTOH, I think the existing approach has a few shortcomings:
  - a user can update his profile info in my application on a settings page, but if he sees user_id_on_provider_plaftorm@loopback.provider.com in the email address field, it's confusing. 
  - Users who sign up via the registration form, end up with a real e-mailadres, while SSO-users with a fake. Each time I want to send a notification from my app to their e-mail, I need to check if it's a real e-mail or not. 
 
It makes the e-mail-property unusable for easy e-mailing purposes, instead it acts as an identifier. I see now this behavior is described in the readMe, but for me it wasn't totally clear until now.

**Comment by Overdrivr** [comment]
You can use the [passport-local](https://github.com/jaredhanson/passport-local) strategy if you want to unify your login strategy.

However, I do agree with you, this approach of using generated emails is really not ideal.

**Comment by ernie58** [comment]
Thx, I'll check it out
