### ISSUE TITLE
Access token instead of session

### ISSUE THREAD

**Issue by cajoy** [strongloop/loopback-component-passport#14]
As I understand passport uses Session/Cookie for callbacks. While loopback uses AccessTokens for user validation.

Is it possible somehow to redirect using AccessToken and UserId instead of session/cookie?

Thanks

**Comment by OwenBrotherwood** [comment]
+1 interesting

**Comment by asanchezdelc** [comment]
+1

**Comment by aiampogi** [comment]
+1 very nice idea to make it built-in
