### ISSUE TITLE
Fails to redirect after auth, "500 InternalOAuthError: Failed to obtain access token"?

### ISSUE THREAD

**Issue by tconroy** [strongloop/loopback-component-passport#143]
Hi!

I'm trying to use Loopback + loopback-component-passport to authenticate against a Github Enterprise server. I've customized a version of the github passport strategy to point to my enterprise API endpoints. I've configured the Server similarly to the facebook demo here: https://github.com/strongloop/loopback-example-passport

I can tell the user is authenticating, because they are shown as authenticated with the app in the github dashboard. However, the app seems to be unable to find the auth token. 

The page the error occurs on has a URL of: http://0.0.0.0:3000/auth/github/callback?code=dceef2ffe07b5dbfa164

isn't `callback?code=` the code? Why am I not sent along to the `successRedirect` defined in my providers?

Thank you for any help!!!

**Comment by richardpringle** [comment]
Hey @tconroy, I don't really have enough info to help with this. Can you reproduce with facebook at all or is it just with GH Enterprise that you're having issues?

**Comment by tconroy** [comment]
Heya @richardpringle, thanks for getting in touch.

I just cloned down the `loopback-example-passport` repo and followed along for a facebook app -- it seems to work as expected. I'm unsure why it fails with github since they both follow similar oAuth2 workflow. So I'd say it's just with GH Enterprise. Unfortunately, this app must authenticate through GH Enterprise. 

The only thing I can really think of that may cause an issue is I had to modify the endpoints in `passport-github/lib/strategy.js` module to point away from `github.com` and to my private Enterprise instance:

* `https://github.{my enterprise domain}.com/login/oauth/authorize`
* `https://github.{my enterprise domain}.com/login/oauth/access_token`
* `'https://github.{my enterprise domain}.com/api/v3/user'`

which seems to be in line with the Github Enterprise API docs.


for what it's worth, I'll throw up the contents of my package.json, providers.json, as well as my server code.

**package.json:** https://gist.github.com/tconroy/3694db98a7f2d39f51a8f335cabe9134

**providers.json:** https://gist.github.com/tconroy/58fb236e17786346ef6b9e37de334669

**server.js**: https://gist.github.com/tconroy/16c2c4a9c1767c7fa53f9bbd6bda23f4


Thanks for your help! Let me know if there's any other pertinent info I can provide.

**Comment by richardpringle** [comment]
@tconroy, can you do me another big favor? Can you submit a feature request on [loopback-example-passport](https://github.com/strongloop/loopback-example-passport/issues)? It will mean more coming from a community member than coming from me.

**Comment by tconroy** [comment]
Hi @richardpringle -- sure thing, I posted a request here: https://github.com/strongloop/loopback-example-passport/issues/76
