### ISSUE TITLE
Setting emailOptional to false still tries to create a user when an email does not exist

### ISSUE THREAD

**Issue by alexpls** [strongloop/loopback-component-passport#149]
This issue was initially discussed here: https://github.com/strongloop/loopback-component-passport/pull/70/files#diff-441c92c018846ec2058d6d670e18d258R119

When setting the `emailOptional` config option to `false` a user is still created (unless the user model specifically has a validation requiring an email address).

I was able to reproduce this bug by:
1. Setting the `emailOptional` config option to `false`
2. Authenticating with a profile that doesn't include an email address

**Comment by jannyHou** [comment]
Related fix: https://github.com/strongloop/loopback-component-passport/pull/150
@alexpls Thanks for pointing it out. We will review it asap.
