### ISSUE TITLE
UserIdentity and UserCredential, why not merge into a single model?

### ISSUE THREAD

**Issue by clark0x** [strongloop/loopback-component-passport#15]
They have exactly the same properties, the only difference is **UserIdentity** has a **login** method to login with third party account, while **UserCredential** has a **link** method to link third party account to current user.

But that means, if I have already linked a google account, I can't use google account to login back next time. Because linked accounts store in _UserCredential_ table/collection, while login will only retrieve from _UserIdentity_ table/collection.

So why there are separated?

**Comment by deksden** [comment]
Look in this thread: https://github.com/strongloop/loopback-component-passport/issues/19

**Comment by deksden** [comment]
IMHO, difference of OpenID and OAuth is that OAuth have some ACLs attached to login token, while OpenID is pure login token with 100% access to account.

Than, maybe, you think that UserCreditential is a storage for linked accounts with limited access, while UserIdentity is account with full access. 

Not sure if rare case of storing limited logins is good to include in generic framework.
