### ISSUE TITLE
Profile data are saved as "[object Object]"

### ISSUE THREAD

**Issue by Lughino** [strongloop/loopback-component-passport#151]
Using this module and how db connector mongodb, the "profile" field of the "UserIdentity" model is saved as "[object Object]", instead of containing the object.

Probably not a issue inherent in this module, instead of the loopback-datasource-juggler module.

**Comment by superkhau** [comment]
Would you like to submit a PR or steps to reproduce the issue? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by Lughino** [comment]
Sure!
Here the [repo](https://github.com/Lughino/loopback-sandbox-passport-error-profile)

Hope you help to find the issue.

**Comment by Lughino** [comment]
Ok, my terrible mistake!
You can close this issue!
Sorry for the trouble .

**Comment by tention** [comment]
@Lughino Was this question raised because you can not retrieve the fields value out from the Profile objects?
