### ISSUE TITLE
Provide a way to deny login base on profile get from third-party

### ISSUE THREAD

**Issue by tobernguyen** [strongloop/loopback-component-passport#152]
When implement login with Google for my application, I have a need to only accept email from domain "abc.xyz". But I couldn't find any way to customize as my need.

Is there any way to achieve that? If not, I would happy to make a pull request.

**Comment by jannyHou** [comment]
@tobernguyen I think you can define a custom validator: 
See how to define and use a custom validator by doc: http://apidocs.strongloop.com/loopback-datasource-juggler/#validatable

**Comment by jannyHou** [comment]
@tobernguyen Does the above solution fix your problem? I am glad to discuss here if you need any help.

**Comment by renanwilliam** [comment]
@jannyHou but the custom validor will be called automatically or it's needed include a hook 'before save' to validate?
