### ISSUE TITLE
Social logins generating invalid emails

### ISSUE THREAD

**Issue by jeff3yan** [strongloop/loopback-component-passport#155]
I have had success with most types of social logins, however when I try to use Auth0 (which provides its own system for social login) there is a problem.

If I use Auth0's facebook login for example, it will generate a user model with an email that looks like:
`auth0.facebook|myemail@something.com@loopback.com`

This causes an email validation error, not allowing the user to be created.

**Comment by jannyHou** [comment]
@jeff3yan I belive this is the same problem with https://github.com/strongloop/loopback-component-passport/issues/158

Shall we close this one and keep discussion under that issue?
I copied your question under that one.

**Comment by jeff3yan** [comment]
Sure, that sounds good.
