### ISSUE TITLE
external id containing @ signs - is that supported?

### ISSUE THREAD

**Issue by andrehagemeier** [strongloop/loopback-component-passport#158]
According to the loopback-passport documentation it is expected behavior that external ids will return in this format: uniqueID@loopback.provider.com
If an external ID is in an email format however, the resulting id will look like this:
andre.hagemeier@something.com@loopback.provider.com
The default user schema validates the email field and the validation fails for an email address containing two @ signs.
As a temporary workaround I disabled the validation for the email field in ./common/models/user.js but I was wondering, if that is the best I can do.

The question basically is:
- are external providers allowed to return uniqueIds containing @ signs -> then either the loopback email concatenation should cover this case and prevent the generation of invalid email addresses or maybe the loopback-passport component should ship an adjusted User model that performs a less strict email validation
- if they are not allowed to do that, is there a specification that they need to comply to?

**Comment by andrehagemeier** [comment]
seems to be the same problem as #155

**Comment by jannyHou** [comment]
@andrehagemeier Thanks for bringing up this issue, yeah it's same as #155 

I copied description from @jeff3yan 
```
I have had success with most types of social logins, however when I try to use Auth0 (which provides its own system for social login) there is a problem.

If I use Auth0's facebook login for example, it will generate a user model with an email that looks like:
auth0.facebook|myemail@something.com@loopback.com

This causes an email validation error, not allowing the user to be created.
```

Let's discuss a possible solution here.

**Comment by jannyHou** [comment]
@raymondfeng Users face a validation problem when the external ID is in email format:
> According to the loopback-passport documentation it is expected behavior that external ids will return in this format: uniqueID@loopback.provider.com
If an external ID is in an email format however, the resulting id will look like this:
andre.hagemeier@something.com@loopback.provider.com

Any thought to fix it or avoid this?

**Comment by davidcheung** [comment]
if we provide option for user to customize the generatedEmail as a function would that be good enough? 

something like https://github.com/strongloop/loopback-component-passport/blob/1d662c7ea8e68c1201bd1b5e7a7c821cc4f136ac/lib/models/user-identity.js#L58-L59
```coffeescript
var generatedEmail = typeof options.formatEmail === 'function' ?
      options.formatEmail(provider, profile) :
      (profile.username || profile.id) + '@loopback.' +
      (profile.provider || provider) + '.com';
```

an example of what profile object
```coffeescript
{
  email:"some@email.com"
  first_name:"David"
  gender:"male"
  id:"my-user-id"
  last_name:"Cheung"
  link:"https://www.facebook.com/app_scoped_user_id/my-user-id/"
  locale:"en_GB"
  timezone:-5
  updated_time:"2015-05-31T19:42:13+0000"
  verified:true
}
```

then user can do whatever they want to generate the email
```coffeescript
  c.formatEmail = function(profile) {
    if (/^\S+@\S+$/.test(profile.username)) {
      return profile.username;
    } else {
      return (profile.username || profile.id) + '@loopback.' +
      (profile.provider || provider) + '.com';
    }
  };
```

cc @jannyHou @raymondfeng @bajtos

**Comment by davidcheung** [comment]
perhaps it doesn't need a patch at all, realized [`profileToUser`](https://github.com/strongloop/loopback-component-passport/blob/1d662c7ea8e68c1201bd1b5e7a7c821cc4f136ac/lib/models/user-identity.js#L126) function is already exposed to the user to be overridden, which would allow them to replace the userObject used to create the loopback User object themselves, [this test case](https://github.com/strongloop/loopback-component-passport/blob/1d662c7ea8e68c1201bd1b5e7a7c821cc4f136ac/test/model.user-identity.test.js#L288-L295) would be an example on how to replace the method.

**Comment by andrehagemeier** [comment]
@davidcheung seems to be exactly what I need. I think this is a very common problem with loopback passport strategies, so maybe the documentation should explicitly spell out the option to override this function

**Comment by davidcheung** [comment]
created https://github.com/strongloop/loopback.io/pull/249, can close again once merged
