### ISSUE TITLE
I am not getting refresh token 

### ISSUE THREAD

**Issue by dineshvgp** [strongloop/loopback-component-passport#159]
My providers.json:

```
  "google-login": {
    "provider": "google",
    "module": "passport-google-oauth",
    "strategy": "OAuth2Strategy",
    "clientID": "XXXXXXXXap.apps.googleusercontent.com",
    "clientSecret": "XXXXXXXXXXXX",
    "callbackURL": "/auth/google/callback",
    "authPath": "/auth/google",
    "callbackPath": "/auth/google/callback",
    "successRedirect": "/auth/success",
    "failureRedirect": "/",
    "scope": ["email", "profile"],
    "failureFlash": true
  },
```

My user identitytable has only `{"accessToken":"XXXX"}` in the credentials column.
How can I get refresh token also some thing like this,
`{"accessToken":"XXXX","refreshToken":"YYYYY"}`

**Comment by kashifeqbal** [comment]
Refresh Token field is only present if _access_type=offline_ is included in the authentication request. For details, see Refresh tokens.

**Comment by SyedSulaimanM** [comment]
Hi, i think you missed the link for 'Refresh Token', Can u please share the link.

**Comment by acrodrig** [comment]
I am having the same issue. How do I make passport configurator pass along the `access_type`? I am adding it to the providers JSON with no luck. Thanks!

**Comment by jannyHou** [comment]
@dineshi2it @SyedSulaimanM @acrodrig Does this solution work? http://stackoverflow.com/questions/8942340/get-refresh-token-google-api

**Comment by royklopper** [comment]
Hi @dineshi2it, if you would like to retrieve a refreshToken you indeed need to set "accessType" to "offline"

You can configure your provider as follows:
`{
  "google": {
      "provider": "google",
      "module": "passport-google-oauth",
      "strategy": "OAuth2Strategy",
      "clientID": "{google-client-id}",
      "clientSecret": "{google-client-secret}",
      "callbackURL": "/link/google/callback",
      "authPath": "/link/google",
      "callbackPath": "/link/google/callback",
      "successRedirect": "/account",
      "failureRedirect": "/login",
      "scope": [
        "email",
        "profile"
      ],
      "authOptions": {
        "accessType": "offline",
        "approvalPrompt": "force"
      },
      "link": true,
      "failureFlash": true
    }
}`

See the "authOptions" object which is added to the configuration, this will do the trick (it gets passed along to `passport.authorize`
