### ISSUE TITLE
Cannot make email verification optional anymore

### ISSUE THREAD

**Issue by jameslk** [strongloop/loopback-component-passport#161]
Due to this commit/line:

https://github.com/strongloop/loopback-component-passport/commit/4cf8153a7b11ace76bf75977fa9ca238cf8910ad#diff-0d9ea68c1756ce2fc5c960b5796850aaR307

An email verification check has been hard coded regardless of whether email verification is enabled or not.

**Comment by jannyHou** [comment]
@jameslk I think this pr forces local email verification on purpose. Please take a look at the doc for this change: https://github.com/strongloop/loopback-component-passport/commit/4cf8153a7b11ace76bf75977fa9ca238cf8910ad?diff=split#diff-04c6e90faac2675aa89e2176d2eec7d8R13

**Comment by jameslk** [comment]
@jannyHou In the documentation for user registration, there appears to be an option to enable and disable email verification, and it's disabled by default:

https://docs.strongloop.com/display/public/LB/Registering+users#Registeringusers-Verifyingemailaddresses

So if email verification is not an option, perhaps the documentation needs to be updated. However,  I think some (including myself) may need to allow registration without email verification, for example for internal applications where only employees might be using it.

**Comment by jannyHou** [comment]
@loay Could you help confirm that the option for emailValidation is removed? Thanks!
And any thought about:
> So if email verification is not an option, perhaps the documentation needs to be updated. However, I think some (including myself) may need to allow registration without email verification, for example for internal applications where only employees might be using it.

?

@jameslk Thanks for pointing out the difference between doc and code. We will update it then!

**Comment by loay** [comment]
Hi @jameslk @jannyHou 
Thanks for pointing this out. 
yes, as stated in the `readme.md` file, all local accounts require verification for security reasons. I will look into the document updates, as well  giving the options as well. I will get back to you on this part. 

in the mean time, you have two options: 
- revert back the back to give the option not to verify the email.
- set by default emailVerification to true.

**Comment by jduhls** [comment]
Can anyone speak about the security implications of honoring user model options per loopback docs similar to:

`if (ok && (user.emailVerified || !self.userModel.settings.emailVerificationRequired))`

re: https://github.com/strongloop/loopback-component-passport/commit/4cf8153a7b11ace76bf75977fa9ca238cf8910ad#diff-0d9ea68c1756ce2fc5c960b5796850aaR307

**Comment by chkuendig** [comment]
I just ran into the same issue. I'm working on an app where signup-friction is a massive concern. Any way to resolved this without resorting to our passport integration?

**Comment by mackwan84** [comment]
+1 I am also facing the same issue. Since in China, email is not so popular for the public. Is hard for us to require email account during registration.

**Comment by haotangio** [comment]
Hi all,

Any update for this issue?
The library is quite useful but this issue is very annoying.
