### ISSUE TITLE
Loopback passport local strategy and angular lb-services component

### ISSUE THREAD

**Issue by hackerunet** [strongloop/loopback-component-passport#164]
Hello, I've been using loopback and a basically hardcoded passport integration into my loopback application that is causing me more pain that usefull solutions, so I need some answers to be able to determine what would be the best and continue.
1) Is it possible to use passport with loopback and declare a login route to render a specific layout / view in EJS which will also use angular lb-services to have the full solution working (authentication, server side protected views and routing)??
2) Angular uses a service that intercepts all queries and adds the access token automatically to the angular controllers, so if I use passport would I still be able to use transparently passport and angular component generated with loopback as well? which means that after login with passport the angular part will get the access token permanently added to every request made from the angular application.
3) is possible to render a different layout/view depending on the user role to render different applications based on user role?
4) Is possible to add more variables to the passport service like accountId, companyId, expiration_date and decide if the account has no pending billings for example and restrict the access or grant access ??
5) How can I have customized variables persisted in the local storage after login and served to the angular application?
regards

**Comment by git2g** [comment]
+1

**Comment by aswin5** [comment]
+1

**Comment by jannyHou** [comment]
Could someone from @strongloop/sq-lb-epitome continue taking care of this issue? Not quite familiar with angular :( Thanks a lot.

**Comment by hackerunet** [comment]
A year later and no further comments nor any suggestions or answers, this is why I stop using strongloop, don't know how it is sponsored by IBM but they don't take care of the community.
Regards.
