### ISSUE TITLE
How to create UserIdentity model?

### ISSUE THREAD

**Issue by gopidon** [strongloop/loopback-component-passport#17]
The model doesn't seem to be a built in model in loopback 2.0. Its not present in the model-config.json file along with other built-in models such as User, Role etc. I tried manually adding it to this json fileand I get the following error. 

Error: Model not found: UserIdentity
    at Function.registry.getModel (/Users/.../node_modules/loopback/lib/registry.js:202:9)

**Comment by FreakTheMighty** [comment]
@gopidon can you share what you figured out?
