### ISSUE TITLE
Issues with openid connect strategy around user's email and accessTokens when trying to authenticate from the callback url

### ISSUE THREAD

**Issue by git2g** [strongloop/loopback-component-passport#173]
Two issues with openidconnect strategy when calling passport.authenticate using either default or customCallback: 
- When the user.email has a email id (such as `x@us.ibm.com`), [you guys are appending @loopback.provider.com](https://github.com/strongloop/loopback-component-passport/blob/master/lib/models/user-identity.js#L58) which is failing with dao.js:

```
name: 'ValidationError',
  message: 'The `user` instance is not valid. Details: `email` Must provide a valid email (value: "x@us.ibm.com@loop...com").',
  statusCode: 422,
  details: 
   { context: 'user',
     codes: { email: [Object] },
     messages: Errors { email: [Object] } } }
ValidationError: The `user` instance is not valid. Details: `email` Must provide a valid email (value: "x@us.ibm.com@loop...com").

```
- Another issue has to do with [user.accessTokens](https://github.com/strongloop/loopback-component-passport/blob/master/lib/models/user-identity.js#L47) returning undefined at [this](https://github.com/strongloop/loopback-component-passport/blob/master/lib/models/user-identity.js#L47) point. Why can't you use user.createAccessToken - as that function seems to be available:

![image](https://cloud.githubusercontent.com/assets/18152044/17652886/8529b5f8-624e-11e6-8921-e8f47bc06921.png)

![image](https://cloud.githubusercontent.com/assets/18152044/17652888/8d2bd2a4-624e-11e6-8c95-213e92305e2d.png)

**Comment by Freundschaft** [comment]
which openid connect strategy are you using? https://github.com/jaredhanson/passport-openidconnect?

**Comment by git2g** [comment]
@Freundschaft - [https://www.npmjs.com/package/passport-idaas-openidconnect](https://www.npmjs.com/package/passport-idaas-openidconnect)

**Comment by Freundschaft** [comment]
I think you can fix this by customizing profileToUser in the providers.json

https://groups.google.com/forum/#!topic/loopbackjs/vTZdq8W9BU4
