### ISSUE TITLE
link is not working. Always req.user undefined!

### ISSUE THREAD

**Issue by ahmed-abdulmoniem** [strongloop/loopback-component-passport#174]
Hi Guys,

Any clue on this discussion

https://groups.google.com/forum/#!msg/loopbackjs/JGPmOiwWr2U/PkJF3KkMWkMJ

I created the LoopBack user, logged in, and then tried `/link/facebook`. Upon successful Facebook login, I got the profile returned. However, the `req.user` is undefined, and I got `done('No user is logged in')` at line `297` of `passport-configurator.js`. Any idea why the `user` is not there?

`loopback-component-passport/lib/passport-configurator.js:`

```
292          if (link) {
293            if (req.user) {
294              self.userCredentialModel.link(req.user.id, name, authScheme, profile,
295                {accessToken: accessToken, refreshToken: refreshToken}, options, done);
296            } else {
297              done('No user is logged in');
298            }
```

Also, I have tried to call `/link/facebook` by passing the loopback token with the link like that `/link/facebook?access_token=###` and still the same!!

Any clue?

**Comment by ahmed-abdulmoniem** [comment]
Any clue guys?

**Comment by ahmed-abdulmoniem** [comment]
Up Guys?!

**Comment by ahmed-abdulmoniem** [comment]
@raymondfeng ?

**Comment by superkhau** [comment]
@davidcheung @richardpringle PTAL

**Comment by ahmed-abdulmoniem** [comment]
Any clue guys!

I am stuck in this issue 3 days now!

@raymondfeng @davidcheung @richardpringle ?

**Comment by ahmed-abdulmoniem** [comment]
Any clue guys!

@raymondfeng @davidcheung @richardpringle ?

**Comment by richardpringle** [comment]
@loay would have a better idea

**Comment by superkhau** [comment]
@ahmed-abdulmoniem Can you provide a sample repo to reproduce the issue? @richardpringle @davidcheung Can you guys confirm the issue reproduction, escalate and assign to @loay accordingly?

**Comment by superkhau** [comment]
@ahmed-abdulmoniem Side note, we all have many priorities on this list to go through and may not get you an answer immediately. If you need support right away, please see our subscription packages at https://strongloop.com/node-js/subscription-plans/

**Comment by ahmed-abdulmoniem** [comment]
It is just simple .. using the example of loopback passport .. I use link

I just want to know if it is working on your side or not guys?

For me it is not .. and many other people are complaining about that!

**Comment by superkhau** [comment]
>It is just simple .. using the example of loopback passport .. I use link

It may be simple, but it still takes us time to reproduce the issue and pinpoint what is going on. That's why we ask for a sample repo on your end so we can skip those details to confirm whether it's an issue with the component or your usage: see https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report.

>I just want to know if it is working on your side or not guys?
If you can provide us a sample repo, we can just run it on our end, confirm the issue and escalate it after confirmation.

>For me it is not .. and many other people are complaining about that!

Those other people are free to +1 this issue you created too and we can bump the priority if there are really are that many users complaining about it.

**Comment by loay** [comment]
Hi @ahmed-abdulmoniem , 
I just tried and it works fine for me. 
Please make sure that you have a valid `client id` and `client secret id` and they are properly inserted in `facebook-login` and `facebook-link` in `providers.json`. 

If it is still not working, we will need a sample app to reproduce as explained by @superkhau 
Thanks.

**Comment by ahmed-abdulmoniem** [comment]
@loay OK I would like to ask if I need to use passport-local as well instead of the normal User.login loopback method?

**Comment by clockworkgr** [comment]
@ahmed-abdulmoniem  Works fine for me. As I mentioned in the google groups thread, make sure you're  making a correctly authenticated request to link/facebook after you've logged in.

Loopback-example-passport is a session-based authentication for example.

You mention passing the access token as a query var (so you're not using the session-based mechanism from loopback-example-passport). I am not sure that works since the user has to be logged in or authenticated on the callback from facebook. So it's the /link/facebook/callback that fb redirects to after authentication that needs the access token/authentication and I don't think that is ever added to the callback url.

If I remember correctly you can only use session/cookie based auth there.

**Comment by ahmed-abdulmoniem** [comment]
I am using session and cookies middleware but I don't know why it is not working!

This is my server file:

```
/* jshint maxlen: 500 */

var loopback = require('loopback');
var boot = require('loopback-boot');
var app = module.exports = loopback();
require('loopback-ds-tree-mixin')(app);
var helmet = require('helmet');
var core = require('./lib/app/core');
if (!process.env.NODE_ENV) {
  process.env.NODE_ENV = 'local';
}

app.use(helmet());

var loopbackPassport = require('loopback-component-passport');
var PassportConfigurator = loopbackPassport.PassportConfigurator;
var passportConfigurator = new PassportConfigurator(app);

var flash = require('express-flash');

// attempt to build the providers/passport config
var providers = {};
try {
  var providersPath = null;
  switch (process.env.NODE_ENV) {
    case 'local':
      providersPath = './lib/config/providers/providers.local.json';
      break;
    case 'development':
      providersPath = './lib/config/providers/providers.development.json';
      break;
    case 'qa':
      providersPath = './lib/config/providers/providers.qa.json';
      break;
    case 'staging':
      providersPath = './lib/config/providers/providers.staging.json';
      break;
    case 'production':
      providersPath = './lib/config/providers/providers.production.json';
      break;
    default:
      providersPath = './lib/config/providers/providers.local.json';
  }
  providers = require(providersPath);
} catch (err) {
  console.trace(err);
  process.exit(1); // fatal
}

// Bootstrap the application, configure models, datasources and middleware.
// Sub-apps like REST API are mounted via boot scripts.
boot(app, {
  bootDirs: ['./lib/boot'],
  appRootDir: __dirname,
  appConfigRootDir: './lib/config/app',
  modelsRootDir: './lib/config/models',
  dsRootDir: './lib/config/datasources',
  middleware: require('./lib/middleware/middleware.json'),
  env: process.env.NODE_ENV
});

app.use(loopback.cookieParser('weAREiTARget_cookie'));

app.use(loopback.session({
  secret: 'weAREiTARget_cookie',
  saveUninitialized: true,
  resave: true
}));

passportConfigurator.init(false);

// We need flash messages to see passport errors
app.use(flash());

passportConfigurator.setupModels({
  userModel: app.models.Customer,
  userIdentityModel: app.models.userIdentity,
  userCredentialModel: app.models.userCredential
});

Object.keys(providers).forEach(function (strategy) {

  // opts will be in the scope of the callback below.
  var opts = providers[strategy];

  opts.session = opts.session !== false;

  // Now that we added the opts.customCallback, got ahead and run the Configurator.
  passportConfigurator.configureProvider(strategy, opts);
});

var models = app.models();
core.timestamps(models);

app.start = function () {
  // start the web server
  return app.listen(function () {
    app.emit('started');
    console.log('current environment: ', process.env.NODE_ENV);
    console.log('Web server listening at: %s', app.get('url'));
  });
};

// start the server if `$ node index.js`
if (require.main === module) {
  app.start();
}

```

**Comment by ahmed-abdulmoniem** [comment]
BTW my callback URL has the access token returned back from Facebook but because req.user is undefined I go to the failure url

**Comment by clockworkgr** [comment]
The code in the fb callback is likely facebook's access-token...not the LP token...

Anyway, unless you can provide a stripped-down repo to reproduce the issue, it's unlikely anyone can help.

The example implementation in loopback-example-passport works just fine. You log in with a local account and a session is created for that user so all subsequent requests to LB using that session id correctly authenticate the local user. So when you try and link the account the callback function finds that local logged in user and links the accounts.

You must be missing/misconfiguring  something on your implementation. Have a look at: https://github.com/strongloop/loopback-example-passport/blob/master/server/server.js again and try and find the issue

**Comment by ahmed-abdulmoniem** [comment]
If it is session based, then I have my client code (Angular) in totally different separated site (http://localhost:8080) and my back end code (Loopback) in a totally different separated site (http://localhost:3000) ..

So, sessions will not work then because the two sessions are different?

**Comment by flam312** [comment]
@ahmed-abdulmoniem 

It could be that your Angular request is not using the session created for Loopback. After a successful facebook login can you try creating a end point in loopback to return req.user and call that end point directly via the browser to see what that gives you?

**Comment by ahmed-abdulmoniem** [comment]
I don't have that much control after login directly I am redirected to facebook callback which redirects me to the failure page all from within loopback-component-passport ..

How to create such end point in between this process?

**Comment by flam312** [comment]
Ok lets take a step back. Can you login with the local account you are trying to link with facebook and then hit the new end point to return a logged in user. It can be as simple as:

app.get('/whoami', function(req, res){
  if(req.user) res.json(req.user);
  else res.send(‘No User’);
});

If you still don't get a user then there maybe a problem with your session config.

**Comment by ahmed-abdulmoniem** [comment]
I am using Angular SDK and User.login method .. so I am not creating custom vanilla express end points .. I am using remote methods.

In remote methods I receive the access token correctly.

**Comment by ahmed-abdulmoniem** [comment]
I have added the end point as you advised and I received no user!

**Comment by ahmed-abdulmoniem** [comment]
This is my configuration:

```
app.use(loopback.cookieParser('secret'));

app.use(loopback.session({
  secret: 'secret',
  saveUninitialized: true,
  resave: true
}));
```

**Comment by ahmed-abdulmoniem** [comment]
@flam312 Any clue? Or something I should change in my configurations?

**Comment by flam312** [comment]
@ahmed-abdulmoniem 

I was rereading this thread and I believe you have to use passport-local to login instead of the default User.login. I tried logging in to a local account using User.login and that does not create a session for me. All of my projects have a login end point defined at the express level much like the passport example:

https://github.com/strongloop/loopback-example-passport/blob/master/server/server.js

Could you try login using passport-local and then hitting the end point that returns req.user to see if the user is being saved? I would also recommend testing these endpoints outside of angular just so you can narrow down the issue.

**Comment by ahmed-abdulmoniem** [comment]
@flam312 This would be a big drawback ..
I am using loopback for a current running application right now with some customers and changing the way we login will affect all of our application logic!

Plus, we have two entities who can login with two different set of properties and business logic (so we can't use roles) and loopback-component-passport only using one entity for the user .. and each two entities need to login/link using Facebook

In that case, I may try to find another solution other than loopback-component-passport unfortunately!

**Comment by regevbr** [comment]
+1

**Comment by huyanhh** [comment]
+1

**Comment by tootle-s** [comment]
+1

**Comment by raul26** [comment]
+1

**Comment by demonVibe** [comment]
+1

**Comment by sbechet** [comment]
Do you do /auth/local or /auth/ldap before /link ?

**Comment by sbechet** [comment]
For `/auth/local` in `middleware.json`, don't forget

```json
"parse": {
    "body-parser#urlencoded": {"params": { "extended": true }}
},
```

**Comment by mien** [comment]
+1
