### ISSUE TITLE
Allow single page application Login via Facebook (client login)

### ISSUE THREAD

**Issue by ddelizia** [strongloop/loopback-component-passport#177]
I have been using loopback-component-passport with facebook login flow. As I'm moving to a single page app, I'm doing the facebook login using the FB sdk as described here: https://developers.facebook.com/docs/facebook-login/web

```
{
  "facebook": {
    "provider": "facebook",
    "module": "passport-facebook",
    "clientID": "<id>",
    "clientSecret": "<secret>",
    "callbackURL": "/auth/facebook/callback",
    "authPath": "/auth/facebook",
    "callbackPath": "/auth/facebook/callback",
    "successRedirect": "/auth/account",
    "failureRedirect": "/login",
    "scope": [
      "email"
    ],
    "failureFlash": true
  }
}
```

I'm able to retrieve the FB access token with the FB sdk, and sending the `response.authResponse.accessToken` value to `GET http://localhost:3000/auth/facebook/callback?access_token=<token from FB sdk response>` but I get an html response.

Am I doing something wrong or loopback does not support this feature?

**Comment by loay** [comment]
Hi @ddelizia 
Please follow this thread: https://github.com/strongloop/loopback-example-passport/issues/11
Thanks

**Comment by scottmcdonnell** [comment]
try adding
```
	  "setAccessToken": true,
	  "json": true,
```
