### ISSUE TITLE
Have a mechanism to handle different environments

### ISSUE THREAD

**Issue by acrodrig** [strongloop/loopback-component-passport#182]
My application has different servers for UI and API. As such, the `providers.json` redirect URLs need to be different (they are absolute URLs). I would love to have a similar mechanism to Loopback, where I could define different providers for different environments:

1. `providers.json` for production
1. `providers.staging.json` for staging
1. `providers.development.json` for development

All of these of course loaded on basis of `NODE_ENV` in the same way that Loopback works. I would love to know if 1) it is on the roadmap, and 2) what current workarounds can I use.

**Comment by loay** [comment]
Hi @acrodrig 
Unfortunately, no it is not on the `soon-to-be-done` roadmap. 
You can submit a PR if you have a work around or I can make a feature request for you. 
The current workaround would be editing the server.js file as in here: https://docs.strongloop.com/display/public/LB/Configuring+providers.json
You can have the three files there and change it according to your needs and comment out the unneeded ones.

**Comment by acrodrig** [comment]
Sounds good. I think it should be easy enough to load a different `provider.json` file based on the `NODE_ENV` variable. Thanks. Consider it solved on my end.
