### ISSUE TITLE
Local Passport: ReferenceError: login is not defined

### ISSUE THREAD

**Issue by derdeka** [strongloop/loopback-component-passport#184]
Hi everyone,

i tried to setup local passport auth with loopback-component-passport 2.2.0. I'm using node 6.3.1
When setting the option setAccessToken to true, i get a reference error "login is not defined".

It seems that the function login at passport-configurator.js@L297 is used before it is defined.

This is the stacktrace i get:

> stack:
   [ 'ReferenceError: login is not defined',
     '    at C:\\Projekte\\lbtest\\server\\node_modules\\loopback-component-passport\\lib\\passport-configurator.js:297:21',
     '    at C:\\Projekte\\lbtest\\server\\node_modules\\loopback-datasource-juggler\\lib\\dao.js:2008:5',
     '    at C:\\Projekte\\lbtest\\server\\node_modules\\loopback-datasource-juggler\\lib\\dao.js:1936:9',
     '    at C:\\Projekte\\lbtest\\server\\node_modules\\loopback-datasource-juggler\\node_modules\\async\\lib\\async.js:396:17',
     '    at done (C:\\Projekte\\lbtest\\server\\node_modules\\loopback-datasource-juggler\\node_modules\\async\\lib\\async.js:167:19)',
     '    at C:\\Projekte\\lbtest\\server\\node_modules\\loopback-datasource-juggler\\node_modules\\async\\lib\\async.js:40:16',
     '    at C:\\Projekte\\lbtest\\server\\node_modules\\loopback-datasource-juggler\\node_modules\\async\\lib\\async.js:393:21',
     '    at buildResult (C:\\Projekte\\lbtest\\server\\node_modules\\loopback-datasource-juggler\\lib\\dao.js:1902:11)',
     '    at C:\\Projekte\\lbtest\\server\\node_modules\\loopback-datasource-juggler\\lib\\dao.js:1916:13',
     '    at doNotify (C:\\Projekte\\lbtest\\server\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:99:49)',
     '    at doNotify (C:\\Projekte\\lbtest\\server\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:99:49)',
     '    at doNotify (C:\\Projekte\\lbtest\\server\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:99:49)',
     '    at doNotify (C:\\Projekte\\lbtest\\server\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:99:49)',
     '    at doNotify (C:\\Projekte\\lbtest\\server\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:99:49)',
     '    at Function.ObserverMixin._notifyBaseObservers (C:\\Projekte\\lbtest\\server\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:122:5)',
     '    at Function.ObserverMixin.notifyObserversOf (C:\\Projekte\\lbtest\\server\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:97:8)' ] }

This is my provider configuration:
>   "local": {
    "provider": "local",
    "module": "passport-local",
    "usernameField": "username",
    "passwordField": "password",
    "authPath": "/auth/local",
    "successRedirect": "/auth/success",
    "failureRedirect": "/auth/failure",
    "failureQueryString": true,
    "setAccessToken": true,
    "session": false
  }

Is this a node6 specific issue?

**Comment by loay** [comment]
@derdeka I am having a look. 
Was it working on a previous node version and it stopped working in node6?

**Comment by loay** [comment]
Hi @derdeka 

in file `lib\passport-configurator.js`,  line 301:
replace:
```
                login = function(creds) {
```
by

```
              function login(creds) {
```

I will fix it in the main repo and try to get it released ASAP. Thanks.

**Comment by loay** [comment]
Issue is fixed. Closing
