### ISSUE TITLE
url param response instead of json

### ISSUE THREAD

**Issue by scottmcdonnell** [strongloop/loopback-component-passport#193]
Currently my react app is opening the api passport auth  in a pop up and listening for the json response  (provider has  `"json": true `) .  
This works fine but the json response is visible before the popup closes. 

Is there a way instead to have the access_token and userId instead set as URL params so they can be read without being visible?

**Comment by chernomord** [comment]
I was searching for the answer too and looks like found a solution.

In the provider configuration you could add field `"session":false`, it would tell the component to add access-token and user-id parameters to the success callback URL

Hope it will help
