### ISSUE TITLE
Integrate passport-jwt

### ISSUE THREAD

**Issue by Freundschaft** [strongloop/loopback-component-passport#201]
Hi there,

I am using https://github.com/themikenicholson/passport-jwt and want to use it together with loopback component passport, but apparently it's kind of hard to use it if I don't add another authscheme to loopback-component-passport.

I made a start by using https://github.com/gfnork/loopback-component-passport/commit/b073efdb7cc515c5904adf67f71a243166bf15e7

Am I mistaken there? Is that the correct approach? Any remarks would be appreciated!

### Bug or feature request

- [ ] Bug
- [X] Feature request

**Comment by smith64fx** [comment]
@Freundschaft 
Your changes look goid.

Is it working or what are the problems exactly?

**Comment by Freundschaft** [comment]
its working actually, just wanted someone to have a look and check if its useful for merge or not

**Comment by raymondfeng** [comment]
@Freundschaft Would you like to contribute a PR?

**Comment by Freundschaft** [comment]
can do, will need 2 weeks before I can get to it, but sure

**Comment by paulcedrick** [comment]
Is this already integrated in the repository? :)

**Comment by malenage** [comment]
Hi @Freundschaft, do you have an example of passport-jwt integrated to loopback-component-passport, i could not find any examples out there. Thanks!
