### ISSUE TITLE
UserIdentity.profileToUser(...) Not Setting To Email Returned By Facebook

### ISSUE THREAD

**Issue by tamitutor** [strongloop/loopback-component-passport#215]
# Description/Steps to reproduce
I have a user in my user table that has an email associated with a Facebook account.  If they go to login with Facebook for the first time--after already having created a user account through local passport--the` UserIdentity.profileToUser(...)` function is not returning a [userObj](https://github.com/strongloop/loopback-component-passport/blob/master/lib/models/user-identity.js#L126) with the email returned by Facebook.

The profile object passed in to `UserIdentity.profileToUser(...)` DOES in fact have an email address in the first index of the array profile.emails.  

However, stepping through the code I discovered this [line](https://github.com/strongloop/loopback-component-passport/blob/master/lib/models/user-identity.js#L60).  This is NOT an "ldap" provider as it's OAuth2/Facebook so the logic on this line is forcing the creation of a dummy email address--which makes no sense...since we have a legit email address from Facebook.  

Further on down in UserIdentity.js it will perform a [`user.findOrCreate({where: query})`](https://github.com/strongloop/loopback-component-passport/blob/master/lib/models/user-identity.js#L146).  It won't find the user that already exists in the user table with the email address returned by Facebook, (again because of the faulty logic cited in the previous paragraph), so it will unnecessarily create another user (with the dummy email address created in "UserIdentity.profileToUser(...)"

# Expected result

A [userObj](https://github.com/strongloop/loopback-component-passport/blob/master/lib/models/user-identity.js#L126) with the actual email address from Facebook login.

# Additional information

darwin x64 6.7.0
├── loopback@3.4.0
├── loopback-boot@2.23.0
├── loopback-component-passport@3.2.0
├── loopback-component-storage@3.1.0
├── loopback-connector-mongodb@3.0.1
├── loopback-context@3.0.0
├── loopback-explorer@1.8.0
├── loopback-objectid-mixin@1.0.1

**Comment by clockworkgr** [comment]
It's a security issue...

Assume you have a sensitive loopback service created (say a financial one)...

Your user has registered for it using a standard email auth providing his e-mail and a strong password he keeps very safe.

One day he leaves his PC unattended in the office to go get some coffee while logged in on facebook.

Some 3rd party visits your service through his browser, chooses log in/sign up via facebook, findOrCreate returns his actual account...boom...Youve just downgraded what the user thinks is a very secure mechanism to the security of his facebook account

**Comment by clockworkgr** [comment]
Linking should only work IF the user is already logged in to his "main" account

**Comment by tamitutor** [comment]
Thank you for relating the security issues surrounding this but how does this help me re-auth a user that's already in the db?  It doesn't--it creates a new user and now my data is corrupt.
