### ISSUE TITLE
Passport with Github: Error: cookieParser("secret") required for signed cookies

### ISSUE THREAD

**Issue by michaelerobertsjr** [strongloop/loopback-component-passport#216]
Using passport and github to auth, seems like there is a bug and the middleware is not setting the secret cookie correctly.

# Description/Steps to reproduce

Attempt to login using link to login with github.  User will be redirected to github, authorize the app and the callback redirects back to the loopback site.  Then an error is thrown and the user is not logged in.  Server shows an error message and according to debugger this.req.secret is not getting set.

Error:

Unhandled error for request GET /auth/github/callback?code=22aaf86d77b5a3582f04: Error: cookieParser("secret") required for signed cookies

# Expected result

It should allow the user to be directed to an authenticated route.

# Additional information

Here is the relevant code that appears to be configured correctly in server.js:

```
// The access token is only available after boot
app.middleware('auth', loopback.token({
  model: app.models.accessToken,
}));
app.middleware('session:before', cookieParser(app.get('cookieSecret')));
app.middleware('session', session({
  secret: 'XXXXXXX',
  saveUninitialized: true,
  resave: true,
}));
passportConfigurator.init();
```

Here is a bit more of the stack trace:
```
Unhandled error for request GET /auth/github/callback?code=22aaf86d77b5a3582f04: Error: cookieParser("secret") required for signed cookies
    at ServerResponse.res.cookie (/Users/michaelrobertsjr/projects/start_now/starkiller/node_modules/express/lib/response.js:791:11)
    at /Users/michaelrobertsjr/projects/start_now/starkiller/node_modules/loopback-component-passport/lib/passport-configurator.js:470:21
    at /Users/michaelrobertsjr/projects/start_now/starkiller/node_modules/loopback-component-passport/node_modules/passport/lib/http/request.js:60:7
```

**Comment by Sigfried** [comment]
Did you figure it out? I need to use github also and I'm running into the same issue.

**Comment by jmereaux** [comment]
Try to replace:
`app.middleware('session:before', cookieParser(app.get('cookieSecret')));`
by
`app.middleware('session:before', cookieParser('yourSecretKeyForCookies));`

**Comment by rasoolabdi** [comment]
You must call the **cookieParser library** in the **server.js** file of the program as follows so that your program can recognize this library.

 **app.use(cookieParser(process.env.COOKIE_PARSER_SECRET_KEY));**
