### ISSUE TITLE
passportConfigurator.setupModels() is not working with my custom userModel.

### ISSUE THREAD

**Issue by taimoor736** [strongloop/loopback-component-passport#238]
What i did is copied the server.js file from this repo [loopback-example-passport](https://github.com/strongloop/loopback-example-passport) and just changed the userModel to my custom model. When i hit the /auth/facebook route its not creating the user inside my custom model but instead create a user in Default User model provided by loopback.
Please help me out.

**Comment by tom-miseur** [comment]
The advice posted on the official Loopback documentation recommends extending the built-in models, yet this component requires a lot of modifications in order for that to be made possible, despite appearing to support model extensions via _setupModels()_.

Furthermore, the concept of "linking" accounts doesn't match what I think most people's assumptions would be with it, that is to say, having a single "master" user account that is able to authenticate with whichever providers were registered, as well as being able to pull data from them once linked.

The article [here](https://scotch.io/tutorials/easy-node-authentication-linking-all-accounts-together) more closely matches my expectations with what this component would provide.

It has definitely been a learning experience trying to work with the component, but at this point I'm much more inclined to simply use Passport directly.

Unfortunately I'm very new to Node.js and Loopback, and so I don't think I'll be able to contribute anything of sufficient quality to address these issues, beyond suggestion documentation edits. I would also appreciate if anyone could prove my synopsis here wrong.

@taimoor736 I managed to progress somewhat by uninstalling this module and using **loopback-passport-component-c** instead as it essentially fixes the problem you are facing. It is discussed [here](https://github.com/strongloop/loopback-component-passport/issues/95). However, if you plan on linking accounts in the way I've described, I would recommend using Passport directly instead as this module makes it rather tedious!
