### ISSUE TITLE
Swagger Documentation for Thirdparty auth api's for LDAP

### ISSUE THREAD

**Issue by kgrvamsi** [strongloop/loopback-component-passport#258]
How can we enable the thirdparty LDAP authentication api's shown in the Swagger Documentation?Any work around for this?

**Comment by dhmlau** [comment]
@kgrvamsi , have you checked out the following tutorials?
https://loopback.io/doc/en/lb3/Tutorial-third-party-login.html#tutorial---ldap
https://developer.ibm.com/recipes/tutorials/configuring-tokenbased-ldap-authentication-with-loopback-io-2/

**Comment by kgrvamsi** [comment]
@dhmlau Thanks for your response and i can implement everything that is been provided in the above two tutorial links but my question is more on how i can make the /auth/ldap route available over Swagger docs?

**Comment by dhmlau** [comment]
I'm not very familiar with LDAP. 
@bajtos @raymondfeng , could you please help?  Thanks.

**Comment by kgrvamsi** [comment]
Can anyone help me on this been so long waiting for someone to answer this request
