### ISSUE TITLE
Example using it with AngularJS client

### ISSUE THREAD

**Issue by douglascorrea** [strongloop/loopback-component-passport#26]
Hi!
First of all, congratulations to the job you are doing with Loopback. It is just awesome.

I'm looking for using social logins + email/password in application that using AngularJS as client.

The ng-lb generator generates the login and logout for user/pass authentication, but I'm looking for extendind it to provide also Facebook, Google and Twitter authentication. 

Is there any example of this?

**Comment by superkhau** [comment]
Have you guys tried https://github.com/strongloop/loopback-example-passport

@douglascorrea Is this good to close? Are you still running into issues?

**Comment by douglascorrea** [comment]
ok, we can close it

**Comment by eugenehp** [comment]
@douglascorrea it still not working with the angular directly, so I think this should be re-opened.

**Comment by eugenehp** [comment]
for example

```
    var cookies = $cookies.getAll();
    var currentUserId = cookies['userId'];
    var accessTokenId = cookies['access_token'];

    currentUserId = currentUserId.split('.')[0];
    currentUserId = currentUserId.split(':')[1];

    accessTokenId = accessTokenId.split('.')[0];
    accessTokenId = accessTokenId.split(':')[1];

    console.log('before',LoopBackAuth);
    LoopBackAuth.currentUserId = currentUserId;
    LoopBackAuth.accessTokenId = accessTokenId;
    LoopBackAuth.rememberMe = true;
    LoopBackAuth.save();
    console.log('after',LoopBackAuth);
```

there is an issue on how the passport module passes cookies to the response

**Comment by eugenehp** [comment]
https://gist.github.com/eugenehp/e45537b73d58db33cd80

**Comment by tamitutor** [comment]
+1

**Comment by mehlleniumfalke** [comment]
+1

**Comment by shushree** [comment]
+1

**Comment by jannyHou** [comment]
Is there anyone still running into this issue?
Could you fork this [sandbox](https://github.com/strongloop/loopback-sandbox) and replace with the code that can reproduce this error?

It's a little hard to reproduce an angular related issue without the code. Thanks for understanding.

**Comment by git2g** [comment]
+1
Also, the [example](https://github.com/strongloop/loopback-example-passport) doesn't actually implement an Angular client using lbservices and LoopBackAuth. Having that would help the community.

**Comment by jannyHou** [comment]
@git2g Thank you, your suggestion looks good 👍

**Comment by jannyHou** [comment]
@eugenehp Sorry I am not an expert in setting up angular app lol, could you fork https://github.com/strongloop/loopback-sandbox and replace it with the **FULL** app to reproduce the error? Really appreciate your contribution and time spent on it! Thanks!

**Comment by gvillenave** [comment]
@eugenehp Your issue is because you need to split on the ':' first, and then the '.'. This code is working for me:
`var accessToken = $cookies.get('access_token');
var userId = $cookies.get('userId');
if (accessToken && userId) {
    accessToken = accessToken.split(':')[1].split('.')[0];
    userId = userId.split(':')[1].split('.')[0];
    LoopBackAuth.setUser(accessToken, userId);
    LoopBackAuth.rememberMe = true;
    LoopBackAuth.save();
}`

**Comment by jerowe** [comment]
+1 for having a full example with loopback and passport auth.

Thanks for the great project!
