### ISSUE TITLE
Bug when calling social login when already logged in?

### ISSUE THREAD

**Issue by janober** [strongloop/loopback-component-passport#27]
I tried to implement the social login stuff today in combination with angular. So I was following mainly this document:
http://docs.strongloop.com/display/LB/Third-party+login
And that example:
https://github.com/strongloop/loopback-example-passport

It seems to work now fine. However when I visit the facebook login-link while I am already logged in I get the following error message and then the process dies:
````
/var/www/phonegap/backend/node_modules/loopback-component-passport/lib/models/user-identity.js:142
        return identity.user(function (err, user) {
                        ^
TypeError: Object #<ModelConstructor> has no method 'user'
```

So apart from it not beeing incredible important because normally that button which links to that page would not be visible for logged in users anway, I just wanted to inform you guys. Is also quite possible that I did setup something wrong in that case it would be interesting to know what it is.

Thanks!

**Comment by superkhau** [comment]
@janober Is this good to close? Are you still running into issues?

**Comment by janober** [comment]
Ah sorry yes. Closed...
