### ISSUE TITLE
Compatibility with loopback 4

### ISSUE THREAD

**Issue by malick-it** [strongloop/loopback-component-passport#270]
# Description/Steps to reproduce

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by malick-it** [comment]
Hello

Is this component compatible with loopback 4 please ?

Thanks

**Comment by raymondfeng** [comment]
No, this component expects Express middleware APIs, which are not fully exposed by LoopBack 4 (yet?).

**Comment by malick-it** [comment]
ok thanks dear.

**Comment by dhmlau** [comment]
Closing this issue as answered.
