### ISSUE TITLE
How to make passport local auth work with loopback verify functionality?

### ISSUE THREAD

**Issue by dstroot** [strongloop/loopback-component-passport#30]
I'd like users to validate their emails when signing up.  However the passport local auth never seems to invoke `user.login` which is the function that actually checks if a user is verified.  I'm stumped...

see: https://github.com/strongloop/loopback-faq-user-management/issues/6

**Comment by csvan** [comment]
I ran into a similar problem when trying to get this component to work with the Angular SDK. The problem, as you correctly point out, is that the User.login() function is never invoked when using the local strategy, and hence no validation is carried out, and (importantly for the Angular SDK), no access token is ever generated.

I have currently hacked the component for our internal work, I hope to release these changes as a pull request during the coming weeks depending on how things turn out.

**Comment by dstroot** [comment]
Thanks for letting me know!  Hope to see the PR.

**Comment by csvan** [comment]
https://github.com/strongloop/loopback-component-passport/pull/32

**Comment by britztopher** [comment]
Actually if you set your 'setAccessToken' flag in your providers.json file like so, it will use the User.login   function like so

   "local": {
    "provider": "local",
    "module": "passport-local",
    "usernameField": "email",
    "passwordField": "password",
    "authPath": "/auth/local",
    "successRedirect": "/auth/account",
    "failureRedirect": "/login",
    "setAccessToken": true
  },

But just make sure your username is used for login, as I am using email as login cred, and username is hardcoded in passport-configurator.js file.

**Comment by dstroot** [comment]
I think the pull request above your comment is the one that added "setAccessToken": true

Shame that username is hardcoded as I also use email as the user id.

**Comment by britztopher** [comment]
@dstroot I just added a ticket to see if we can do something about it found here #34

**Comment by dstroot** [comment]
@britztopher - great!  Thanks for that.
