### ISSUE TITLE
dimension of accessToken.ttl [sec] differs from res.cookie maxAge [msec]

### ISSUE THREAD

**Issue by aol-nnov** [strongloop/loopback-component-passport#31]
While accessToken model has the following defaults
```
"ttl": {
      "type": "number",
      "ttl": true,
      "default": 1209600,
      "description": "time to live in seconds (2 weeks by default)"
    },
```
Which, to my understanding, means that loopback internals expect ttl to be in seconds, while res.cookie expects maxAge param to be in milliseconds (http://expressjs.com/4x/api.html#res.cookie).
After that I have my session expire in something 20 minutes instead of two weeks due to the following code in loopback-component-passport: (https://github.com/strongloop/loopback-component-passport/blob/master/lib/passport-configurator.js#L372)
```res.cookie('access_token', info.accessToken.id, { signed: req.signedCookies ? true : false,
                maxAge: info.accessToken.ttl });```

Please advice the correct way around this issue.

Thanks in advance,
Andrey

**Comment by raymondfeng** [comment]
Can you submit a patch to fix https://github.com/strongloop/loopback-component-passport/blob/master/lib/passport-configurator.js#L372?

**Comment by didikeke** [comment]
For this issue, @aol-nnov is right.  

Change codes in https://github.com/strongloop/loopback-component-passport/blob/master/lib/passport-configurator.js to 
```
maxAge: 1000 * info.accessToken.ttl

```
will be fix it.

I am not sure what is @qazs 's pull requests meaning.

**Comment by aol-nnov** [comment]
@raymondfeng sorry for being idle on this issue - been way too busy lately. It was not clear for me what actually needs to be fixed: the code (as @didikeke proposed) by multiplying ttl value by 1000 or just the documentation strings (that input parameter should be in millis)

If no loopback internals expect ttl to be in milliseconds, I'd opt to @didikeke's approach. Otherwise, I vote for fixing the docs.

**Comment by didikeke** [comment]
From https://github.com/strongloop/loopback/blob/master/common/models/user.js#L23

the TTL is seconds.
