### ISSUE TITLE
setAccessToken has hardcoded username for login function

### ISSUE THREAD

**Issue by britztopher** [strongloop/loopback-component-passport#34]
I was looking at the switch statement in passport-configurator.js file starting on line 177, and it appears that if you set a flag in your providers.json file for `"setAccessToken" : true` the statement will use the login function attached to the User model.  like so:

```javascript
 self.userModel.login({username: username, password: password},
                    function (err, accessToken) {
                      if (err) {
...
```
This is great, however, most applications use email as the person's username.  Is there a way around this, or do I have to add an if statement to use email if login using username returns nothing?  I would like to have the access token attached to a cookie and sent back to the browser, and this seems to be the only way to accomplish this using local auth.

**Comment by raymondfeng** [comment]
I wonder if we should enhance the User.login so that it can support a property such as `usernameOrEmail`. @ritch ?

**Comment by britztopher** [comment]
@raymondfeng 
well right now the workaround is this 
```javascript
 self.userModel.login({email: username, password: password}, function(err, accessToken)
...
```
so I am guessing that user.login takes email and username already.

**Comment by britztopher** [comment]
Also I am wondering why the access_token isnt sent as a cookie in the response header for auth/local even if the setAccessToken flag is set in providers.json file.  Dont you need an access token to make subsequent authorized calls after logging in?
