### ISSUE TITLE
userProfile not being Created in UserIdentity Collection upon Local Login

### ISSUE THREAD

**Issue by britztopher** [strongloop/loopback-component-passport#37]
It appears that the access_token is being created in local strategy, however, there when logging in using the local strategy the user profile that is created on line 196 in `passport-configurator.js`:

```javascript
 var userProfile = {
                provider: 'local',
                id: u.id,
                username: u.username,
                emails: [
                  {
                    value: u.email
                  }
                ],
                status: u.status,
                accessToken: null
              }; 
```

is never saved to database, which for me, is a mongo collection.  I say this because when I try to get the `req.user` I dont get back the profile for the user, which contains the access token.  I need the access token in a cookie to send back in the response, so that I can make subsequent requests with that logged in user to loopback models.  Is there a reason we dont create a profile for local provider logins, or dont send back the access token for local strategy via cookie?

**Comment by raymondfeng** [comment]
For local login as the user profile is already in the User DB, it makes sense not to save the user profile. We can add the code to store the access_token in cookie though as other schemes does.

**Comment by britztopher** [comment]
@raymondfeng, why do you create the json object if there is no reason for storing it?  Also, wouldnt it be beneficial to create a user structure that is consistent with other social accounts.  For example, my profile picture url now will have to be saved in both local and social if I were to login using both strategies then do a check on the client for which one to use.  

AccessToken would be a great addition, any reason why it was left out?

**Comment by julien-sarazin** [comment]
@raymondfeng is it possible to store the access_token in cookie now?

**Comment by loay** [comment]
@britztopher 
Is this issue still persisting? Thanks

**Comment by jannyHou** [comment]
I am closing it since it's too long ago to track, please feel free to reopen it if anyone still has problem. Thanks for understanding.
