### ISSUE TITLE
get profile information in new style hooks

### ISSUE THREAD

**Issue by BerkeleyTrue** [strongloop/loopback-component-passport#41]
I am trying to build a base profile out using loopbacks new hook syntax. It seems that using the `before save` method does not expose the data user creation using this component. Is it possible to get that information directly on the hook?

cc @QuincyLarson @terakilobyte

**Comment by superkhau** [comment]
Are you still running into this issue? Would you like to submit a PR?

**Comment by BerkeleyTrue** [comment]
Not sure how we got around this so I'm closing.
