### ISSUE TITLE
Error when logging in using passport-local

### ISSUE THREAD

**Issue by qazs** [strongloop/loopback-component-passport#45]
Hi,

I keep getting this error when logging in with the correct username but wrong password:
```
http.js:689
    throw new Error('Can\'t set headers after they are sent.');
          ^
Error: Can't set headers after they are sent.
  at ServerResponse.OutgoingMessage.setHeader (http.js:689:11)
  at ServerResponse.res.setHeader (/usr/src/app/node_modules/loopback-explorer/n
ode_modules/express/node_modules/connect/lib/patch.js:134:22)
  at /usr/src/app/node_modules/errorhandler/index.js:132:15
  at fs.js:271:14
  at Object.oncomplete (fs.js:107:15)

Program node --harmony --debug ./server/server.js exited with code 8
```
This is what's causing the error:
https://github.com/strongloop/loopback-component-passport/blob/master/lib/passport-configurator.js#L228

I believe changing to this will fix this issue:
```
return done(null, false, {message: 'Incorrect password.'});
```

**Comment by superkhau** [comment]
Would you like to submit a pull request?

**Comment by terusus** [comment]
This is still a thing in 2.0.0. And that line of code is not a fix.

if we have `"setAccessToken": true` in `providers.json` then one of the `done(...)` functions on line [308](https://github.com/strongloop/loopback-component-passport/blob/v2.0.0/lib/passport-configurator.js#L308) or [310](https://github.com/strongloop/loopback-component-passport/blob/v2.0.0/lib/passport-configurator.js#L310) is called always before the `done(...)` functions in the [`login(...)` function](https://github.com/strongloop/loopback-component-passport/blob/v2.0.0/lib/passport-configurator.js#L287) on line [295](https://github.com/strongloop/loopback-component-passport/blob/v2.0.0/lib/passport-configurator.js#L295) or [297](https://github.com/strongloop/loopback-component-passport/blob/v2.0.0/lib/passport-configurator.js#L297).

**Comment by terusus** [comment]
This is still a thing in __v2.0.0__. When this happens:

`"setAccessToken": true` in `providers.json`. A new user is created (`user.emailVerified === false`). That user tries to login before email verification. He will not login. But the server throws _Error: Can't set headers after they are sent_.

Reason: [Login function](https://github.com/strongloop/loopback-component-passport/blob/v2.0.0/lib/passport-configurator.js#L287) is called after line [310](https://github.com/strongloop/loopback-component-passport/blob/v2.0.0/lib/passport-configurator.js#L310) or [314](https://github.com/strongloop/loopback-component-passport/blob/v2.0.0/lib/passport-configurator.js#L314)

**Comment by terusus** [comment]
Also, when we override the default login behavior with a hook. We would like to actually use user.login(...). For example, if the user has a user.loginEnabled flag we would be in the same situation:
Passport authenticates successfully but getting an access token fails and we get an error.

**Comment by loay** [comment]
connect to https://github.com/strongloop/loopback-component-passport/pull/136

**Comment by loay** [comment]
Issue is fixed. Closing

**Comment by hackerunet** [comment]
I'm sorry how was it fixed? I have the version "loopback-component-passport": "^2.1.0", installed and I have the headers problem.
I have in passport.json:
`{
  "local": {
    "provider": "local",
    "module": "passport-local",
    "usernameField": "email",
    "passwordField": "password",
    "authPath": "/auth/local",
    "successRedirect": "/private",
    "failureRedirect": "/login",
    "failureFlash": true,
    "setAccessToken": true
  },
  "facebook-login": {
    "provider": "facebook",
    "module": "passport-facebook",
    "clientID": "{facebook-client-id-1}",
    "clientSecret": "{facebook-client-secret-1}",
    "callbackURL": "/auth/facebook/callback",
    "authPath": "/auth/facebook",
    "callbackPath": "/auth/facebook/callback",
    "successRedirect": "/private",
    "failureRedirect": "/login",
    "scope": ["email"],
    "failureFlash": true
  }
}
`
I'm only testing local directive for now. and this is my server.js
`'use strict';

var loopback = require('loopback');
var boot = require('loopback-boot');
var app = module.exports = loopback();
var bodyParser = require('body-parser');
var cookieParser = require('cookie-parser');
var session = require('express-session');
var flash = require('express-flash');
var secret = require('../config/secret.json').cookieSecret;

// Passport configurators..
var loopbackPassport = require('loopback-component-passport');
var PassportConfigurator = loopbackPassport.PassportConfigurator;
var passportConfigurator = new PassportConfigurator(app);

// attempt to build the providers/passport config
var config = {};
try {
  config = require('../config/passport.json');
} catch (err) {
  console.trace(err);
  process.exit(1); // fatal
}

// to support JSON-encoded bodies
app.middleware('parse', bodyParser.json());
// to support URL-encoded bodies
app.middleware('parse', bodyParser.urlencoded({
  extended: true
}));

// The access token is only available after boot
app.middleware('auth', loopback.token({
  model: app.models.AccessToken
}));

app.middleware('session:before', cookieParser(app.get('cookieSecret')));
app.middleware('session', session({
  secret: secret,
  saveUninitialized: true,
  resave: true
}));

passportConfigurator.init();

boot(app, __dirname);

// We need flash messages to see passport errors
app.use(flash());

passportConfigurator.setupModels({
  userModel: app.models.sentinel_account,
  userIdentityModel: app.models.sentinel_identity,
  userCredentialModel: app.models.sentinel_credential
});
for (var s in config) {
  var c = config[s];
  c.session = c.session !== false;
  passportConfigurator.configureProvider(s, c);
}

require('../config/routes.js')(app);

app.start = function() {
  // start the web server
  return app.listen(function() {
    app.emit('started');
    var baseUrl = app.get('url').replace(/\/$/, '');
    console.log('Web server listening at: %s', baseUrl);
    if (app.get('loopback-component-explorer')) {
      var explorerPath = app.get('loopback-component-explorer').mountPath;
      console.log('Browse your REST API at %s%s', baseUrl, explorerPath);
    }
  });
};

// start the server if `$ node server.js`
if (require.main === module) {
  app.start();
}
`
And i have an external file with routes:
`module.exports = function(app) {
  var path = require('path');
  var expressLayouts = require('express-ejs-layouts');
  var router = app.loopback.Router();
  var ensureLoggedIn = require('connect-ensure-login').ensureLoggedIn;

  // Setup the view engine (jade)
  var path = require('path');
  app.set('views', path.join(__dirname, '../server/views'));
  app.set('view engine', 'ejs');
  app.use(expressLayouts);



  router.get('/', function (req, res, next) {
    res.render('pages/index', {
      user: req.user,
      url: req.url,
    });
  });

  router.get('/auth/account', ensureLoggedIn('/login'), function (req, res, next) {
    res.render('pages/loginProfiles', {
      user: req.user,
      url: req.url,
    });
  });

  router.get('/private', ensureLoggedIn('/login'), function (req, res, next) {
    res.render('private/app.ejs', {
      user: req.user,
      url: req.url,
      layout:'layouts/app.ejs'
    });
  });

  router.get('/local', function (req, res, next) {
    res.render('pages/local', {
      user: req.user,
      url: req.url,
    });
  });

  router.get('/signup', function (req, res, next) {
    res.render('public/signup.ejs',
      {
        user:req.user,
        url: req.url,
        layout:'layouts/signup.ejs'
      });
  });

  router.post('/signup', function (req, res, next) {
    var User = app.models.sentinel_account;

    var newUser = {};
    newUser.email = req.body.email.toLowerCase();
    newUser.username = req.body.username.trim();
    newUser.password = req.body.password;

    User.create(newUser, function (err, user) {
      if (err) {
        req.flash('error', err.message);
        return res.redirect('back');
      } else {
        // Passport exposes a login() function on req (also aliased as logIn())
        // that can be used to establish a login session. This function is
        // primarily used when users sign up, during which req.login() can
        // be invoked to log in the newly registered user.
        req.login(user, function (err) {
          if (err) {
            req.flash('error', err.message);
            return res.redirect('back');
          }
          return res.redirect('/auth/account');
        });
      }
    });
  });

  router.get('/login', function (req, res, next) {
    res.render('public/login.ejs',
      {
        user:req.user,
        url: req.url,
        layout:'layouts/public.ejs'
      });
  });

  router.get('/auth/logout', function (req, res, next) {
    req.logout();
    res.redirect('/');
  });

  app.use(router);
}
`
Can you see something that may be is replicating the error?
thanks
