### ISSUE TITLE
grant_type client_credentials: req.authInfo.user is filled with first User

### ISSUE THREAD

**Issue by PuKoren** [strongloop/loopback-component-passport#51]
When I log into loopback with oauth2 and using client_credentials type, the req.authInfo.user is always filled with the first inserted user in DB.
Since the first user is admin, that were causing all my apps logging in to be admin (I was using register resolver for ACL based on the user email).

Using loopback 2.14 and loopback-component-oauth2 1.0

**Comment by superkhau** [comment]
Can you provide a link to a test project on Github? See https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by jannyHou** [comment]
I am closing it since it's too long ago. Please feel free to reopen it if you still run into it. Thanks for understanding.
