### ISSUE TITLE
Configurable cookie path

### ISSUE THREAD

**Issue by Darkeye9** [strongloop/loopback-component-passport#52]
Hello!

As I have my app installed on a subdirectory, It would be very helpful to have an option to set the desired path for the cookies. Because using Angular on the client side I cannot manage them correctly.

I can code a PR to support it, but I would like to know which approach is better.
1. Set the cookie path in the providers.json file, for each strategy (not so good)
2. Guess the correct path from the auth request. (ideally?)

Let me know.

Cheers ;)

**Comment by superkhau** [comment]
@raymondfeng Which strategy is recommended?

@Darkeye9 Please feel free to submit a PR.
