### ISSUE TITLE
No access token stored in angular client when logging in with Third Party

### ISSUE THREAD

**Issue by ccgdesigns** [strongloop/loopback-component-passport#56]
Just spent quite a while getting authorization to work for REST requests in my angular app, kept getting 401 Unauthorized.

Essentially, because logging in using facebook (twitter etc.) just involves sending the browser to /auth/facebook and lets passport handle the rest. LoopBackAuth is never configured because User.login() is never called (as it would be with a login form), so none of the requests are signed with the authorisation=access_token header, ergo many 401s..

I have worked around this with a bit of server side templating but would like to know if there is a better way of doing this.

``` jade
script.
      angular.module('app').factory('currentUser', ['LoopBackAuth',function (LoopBackAuth) {
        var user = !{JSON.stringify(user)};
        LoopBackAuth.setUser("!{authToken}", user.id, user);
        LoopBackAuth.rememberMe = true;
        LoopBackAuth.save();
        return user;
      }]);
```

It seems obvious now that I've figured it out but I was wondering if this could be made clearer or be added to the getting started docs.

**Comment by superkhau** [comment]
@raymondfeng Is the process described by the user the recommended way of doing it?

@crandmck May need to update docs according to @raymondfeng's recommendations.

**Comment by crandmck** [comment]
I'm happy to add to the docs.  Just waiting for confirmation and/or clarification from @raymondfeng .

**Comment by DuyHung21** [comment]
@crandmck I'm having the same problem 
And I'm new with this,too
Could you show me how to fix it

**Comment by raymondfeng** [comment]
Now we have multiple ways to receive an access token representing granted permissions. 

1. User.login
2. Third-party login
3. oAuth2 flows

I have started to think about how to unify/federate the different schemes. It probably boils down to a few separate concerns:

1. Authentication (verify credentials to establish a subject)
2. Manage identities, such as user/app/device
3. Access token provisioning and management
4. Deliver the access token to the client side

Some of the high ideas are captured at https://docs.strongloop.com/pages/viewpage.action?pageId=3836277. What we need now is a complete scenario to drive the polishing of the design/impl.

**Comment by barocsi** [comment]
I am facing the similar issue, after the successful login, user data is received, token generated but the Strongloop Angular SDK service never sends access_token with subsequent calls. The docs says:
>Authentication
The SDK provides first-class support for authenticated requests.
Basic use is simple: Call User.login() with correct credentials and the SDK will handle everything else for you. It will store the access token provided in login response and send this token in all subsequent requests.

What is the right way to do this then?

**Comment by crandmck** [comment]
@bajtos Can you comment on the right way to use Angular SDK with loopback-component-passport?

**Comment by bajtos** [comment]
TBH, I don't know what's the right way. We need to set aside some time to investigate what's the best approach here.

**Comment by crandmck** [comment]
OK, it sounds like this is not really a doc issue.  First, the relevant engineers need to determine how to do  it, then explain it to me and ideally provide an example.   I'm going to remove the "doc" label for now.  Can add it back and/or create separate issue when above is done.

**Comment by jayasrinagrale** [comment]
Any recent updates on this guys?
