### ISSUE TITLE
Docs for customCallback

### ISSUE THREAD

**Issue by Gouthamve** [strongloop/loopback-component-passport#58]
I saw that there is an option of specifying custom callback but there is no reference in the docs. 

Also I see that it has to specified in the providers.json but how do I specify a function in JSON?

**Comment by OwenBrotherwood** [comment]
@Gouthamve custom callback was introduced with the support of LDAP https://github.com/strongloop/loopback-component-passport/pull/44 
Documentation is being discussed https://github.com/strongloop/loopback-example-passport/issues/12#issuecomment-96062269 but with reference to the providers.json. 
I had forgot the extra custom callback that was introduced so it is good you created the issue.
