### ISSUE TITLE
AccessToken and cookie TTL mismatch

### ISSUE THREAD

**Issue by javefang** [strongloop/loopback-component-passport#59]
Affecting version 1.3.0

It's the same issue as the one that has been raised by aol-nnov before.
https://github.com/strongloop/loopback-component-passport/issues/31

The issue has been fixed by aol-nnov's pull request #31, commit 893d0c, 
https://github.com/strongloop/loopback-component-passport/commit/893d0c92c9ec18e79b375c5b790cdb17bbd7769c

but the fix has been removed in a later commit 6989f8 (ldap authentication) for some reasons.
https://github.com/strongloop/loopback-component-passport/commit/6989f8ace1b30169a811cc9d658d3565f97d8e4d#diff-0d9ea68c1756ce2fc5c960b5796850aaR428

Thus the current latest version 1.3.0 in npm is broken, which results in the default cookie expiry to be 20min instead of 2 weeks.

**Comment by raymondfeng** [comment]
Good catch. Fixed by https://github.com/strongloop/loopback-component-passport/commit/a307f2f400105ae3c2f191ea2f99a5c3de6d118b
