### ISSUE TITLE
stay at current page after login

### ISSUE THREAD

**Issue by transedward** [strongloop/loopback-component-passport#60]
When I walk through example and document,
Seems currently we only have the option to set successRedirect in providers.json statically,
Do u have support for dynamic successRedirect url in the future?
ex: stay at same page when user submit ted login

or already have it but I missed.
Thanks for any answer and suggestion

**Comment by AlmaasAre** [comment]
This would be awesome to have. Dynamic successredirect is really useful when the client and API is totally disconnected. 

My preferred flow for facebook-auth would be to pass a returnURL in a query param from the client.

**Comment by superkhau** [comment]
Already merged. Closing.

**Comment by pvijeh** [comment]
how is this achieved ?

**Comment by gbhipolitoglyph** [comment]
so how to set successRedirect programmatically?
thanks
