### ISSUE TITLE
Using context to get current user doesnt work

### ISSUE THREAD

**Issue by peterwilli** [strongloop/loopback-component-passport#61]
Hi,

I wanted to get the current user in a remote method. I'm using passport for login right now (mostly copied from example)

I came across contexts: http://docs.strongloop.com/display/RU/Using+current+context
But I cant seem to make passport and contexts work nicely together :(
When calling the method, the error I get is this:

`loopback.token() middleware requires a AccessToken model`

Everything worked fine and I could login and stuff, but just getting context to work is a problem.
If anyone knows how to do this that would be awesome! I have been searching for hours...
I'm writing in coffeescript but I converted to JS so that all users can read it properly ;)

I set up my server using this code:

    var app, boot, flash, loopback;
    
    require('./global');
    
    loopback = require('loopback');
    
    boot = require('loopback-boot');
    
    app = module.exports = loopback();
    
    flash = require('express-flash');
    
    global.app = app;
    
    app.use(flash());
    
    require('./passport').beforeBoot(app);
    
    app.use(loopback.context());
    
    app.use(loopback.token({
      model: 'accessToken'
    }));
    
    app.use(function(req, res, next) {
      if (!req.accessToken) {
        return next();
      }
      app.models.UserModel.findById(req.accessToken.userId, function(err, user) {
        var loopbackContext;
        log('user', user);
        if (err) {
          return next(err);
        }
        if (!user) {
          return next(new Error('No user with this access token was found.'));
        }
        loopbackContext = loopback.getCurrentContext();
        if (loopbackContext) {
          loopbackContext.set('currentUser', user);
        }
        next();
      });
    });
    
    app.use(function(req, res, next) {
      res.header("X-Powered-By", "Blood, sweat, and tears");
      return next();
    });
    
    require('loopback-ds-readonly-mixin')(app);
    
    boot(app, __dirname);
    
    require('./passport').afterBoot(app);
    
    app.start = function() {
      return app.listen(function() {
        app.emit('started');
        console.log('Web server listening at: %s', app.get('url'));
      });
    };
    
    app.get('/login', function(req, res, next) {
      res.send({});
    });
    
    app.get('/auth/logout', function(req, res, next) {
      req.logout();
      res.redirect('/');
    });
    
    app.start();

Passport module is this:

    var PassportConfigurator, ensureLoggedIn, loopbackPassport, passportConfigurator;
    
    loopbackPassport = null;
    
    PassportConfigurator = null;
    
    passportConfigurator = null;
    
    ensureLoggedIn = null;
    
    module.exports = {
      beforeBoot: function(app) {
        var c, config, err, s;
        loopbackPassport = require('loopback-component-passport');
        PassportConfigurator = loopbackPassport.PassportConfigurator;
        passportConfigurator = new PassportConfigurator(app);
        ensureLoggedIn = require('connect-ensure-login').ensureLoggedIn;
        passportConfigurator.init();
        config = {};
        try {
          config = require('../providers.json');
        } catch (_error) {
          err = _error;
          console.trace(err);
          process.exit(1);
        }
        for (s in config) {
          c = config[s];
          c.session = c.session !== false;
          passportConfigurator.configureProvider(s, c);
        }
        return app.get('/auth/account', ensureLoggedIn('/login'), function(req, res, next) {});
      },
      afterBoot: function(app) {
        return passportConfigurator.setupModels({
          userModel: app.models.user,
          userIdentityModel: app.models.userIdentity,
          userCredentialModel: app.models.userCredential
        });
      }
    };
    
    // ---
    // generated by coffee-script 1.9.2

**Comment by raymondfeng** [comment]
There is a typo in your code:
```
app.use(loopback.token({
  model: 'aaccessToken'
}));
```
should be:
```
app.use(loopback.token({
  model: 'accessToken'
}));
```

**Comment by peterwilli** [comment]
@raymondfeng  yeah spotted that (wasnt in the actual code) example should be fixed by now - still the same problem :(. I also tried making an empty project but same thing.

**Comment by peterwilli** [comment]
#UPDATE I GOT IT WORKING!
Way to wrecked right now, will update tomorrow for others with the same issue..

**Comment by peterwilli** [comment]
So the issue was pretty well hidden but I found out after all. And when I did it made much more sense.
The problem is that for loopback.token to work with passport you need to pass on the custom access-token model.

I first did that using a string which didnt seem to work.

Now I do it like this:

    app.use(loopback.context())
    app.use(loopback.token(
      model: app.models.accessToken
    ))

But the main problem is now that app.models.* is only available after boot.
Weirdly enough, app.use functions didnt work after boot (they got ignored)

**Solution**
I found out that rest-api.js in sever/boot was catching the request and doesnt pass it on to other middleware.
It was the end point for rest-requests.

So, I created another boot script and called it '01-token.coffee' (you can use .js if you use js) to make sure it will load before rest-api but after boot.

In this file I got this:

  module.exports = (app) ->
    loopback = require('loopback')
      app.use(loopback.context())
      app.use(loopback.token(
        model: app.models.accessToken
      ))
  
    app.use (req, res, next) ->
      if !req.accessToken
        return next()
  
      app.models.user.findById req.accessToken.userId, (err, user) ->
        if err
          return next(err)
        if !user
          return next(new Error('No user with this access token was found.'))
        loopbackContext = loopback.getCurrentContext()
        if loopbackContext
          loopbackContext.set 'currentUser', user
        next()
  
        return
  
      return

Now I can happily use:

    ctx = loopback.getCurrentContext()
    currentUser = ctx && ctx.get('currentUser')

To get the current user in remote methods ;)
**Hope to have helped other people with this too!** (and that they didnt spend as much time on it as I did ;))

**Comment by guptasujeet** [comment]
> Hope to have helped other people with this too! 

Yeah, I was also struggling for the same, It helped me. 
Thanks !!

**Comment by tyoh** [comment]
How, this works!!!   Thanks so much, peterwilli
