### ISSUE TITLE
how can I know that before loopback-component-passport login or create?

### ISSUE THREAD

**Issue by transedward** [strongloop/loopback-component-passport#63]
for example: if I wanna do something after loopback-component-passport create the user, 
and do other thing before the user login
I thought I can use [remote hooks](http://docs.strongloop.com/display/public/LB/Remote+hooks#Remotehooks-Contextobject) to get the timing I want.
like:

``` js
MyUser.afterRemote('create', function(context, instance, next) {
    // do something here
    next();
  });

  MyUser.beforeRemote('login', function(context, instance, next) {
    // do something here
    next();
  });
```

I found out it didn't work.

so I use [operation hook](http://docs.strongloop.com/display/public/LB/Operation+hooks#Operationhooks-Operationhookcontextobject)

``` js
MyUser.observe('after save', function(ctx, next) {
    if (ctx.instance) {
      // I can know it's a newly created user
    } else {
     // otherwise...
    }
    next();
  });
```

But I still can't get any hint about when I can access before user login?

Did I miss something, or anyone has a better idea about doing the other way?

Diddn't loopback-component-passport use User.login, User.create?

**Comment by mailuser41** [comment]
bump

**Comment by vburghelea** [comment]
+1 I'm also trying to figure out how I can hook into the create account / login process so I can extract Facebook profile information and do some processing.

**Comment by superkhau** [comment]
@bajtos @raymondfeng @ritch I'm not sure about this one. Do you guys know?

**Comment by codeyad** [comment]
Can someone please help with this issue?, im trying to look a way to do it, @bajtos @raymondfeng @ritch could you please look at this?

**Comment by bajtos** [comment]
I am personally not familiar with this module. @raymondfeng could you PTAL yourself?

**Comment by mike-aungsan** [comment]
+1
Trying to do the same and looking for doc.

**Comment by codeyad** [comment]
I probably should do my own passport component

**Comment by ghislaindj** [comment]
Same problem here !

**Comment by saurabh73** [comment]
Any Update on this???

**Comment by BilalDja** [comment]
I guess you can create a customCallback(req, res, next) and call the passport.authenticate(err, user, info)
My personal problem is how to distinguish between a newly created User and just a logged in user??

**Comment by ataft** [comment]
+1
I want to add User role mappings to the response. There's a lot going on in the defaultCallback(), so don't think it's a great idea to rewrite that in the customCallback(), but will if there's no other solution.
