### ISSUE TITLE
Cannot set user without email

### ISSUE THREAD

**Issue by BerkeleyTrue** [strongloop/loopback-component-passport#66]
Most of our users use twitter to login. Twitter does not return emails so we have had it optional in our past setup.

Currently switching to loopback and running into this modul erring when userObj.email is null (which is our default, a lot of our system depends on this so it is not possible to change it).

Would a PR be accepted to add a flag to make email optional?
[here](https://github.com/strongloop/loopback-component-passport/blob/master/lib/models/user-identity.js#L116) and [here](https://github.com/strongloop/loopback-component-passport/blob/master/lib/models/user-identity.js#L50)

from:
```js
// login func
if (!userObj.email) {
    return cb('email is missing from the user profile');
}

// profileToUser
if (options.emailOptional && !email) {
      // Fake an e-mail
      email = (profile.username || profile.id) + '@loopback.' +
              (profile.provider || provider) + '.com';
}
```
to

```js
// login func
if (!userObj.email && !options.emailOptional) {
    return cb('email is missing from the user profile');
}

// profileToUser
if (!email && !options.emailOptional) {
      // Fake an e-mail
      email = (profile.username || profile.id) + '@loopback.' +
              (profile.provider || provider) + '.com';
}
```

cc @terakilobyte @QuincyLarson

**Comment by Gouthamve** [comment]
The problem is User model itself has the email field as required. The user model from swagger interface is given below.

```
User {
realm (string, optional),
username (string, optional),
credentials (object, optional),
challenges (object, optional),
email (string),
emailVerified (boolean, optional),
verificationToken (string, optional),
status (string, optional),
created (string, optional),
lastUpdated (string, optional),
id (objectid, optional)
}
```

**Comment by BerkeleyTrue** [comment]
That is a separate issue that belongs to loopback actual. The problem here is that this module always adds a faux email. Our current setup requires an empty field instead. It is not possible currently.

I believe user model in loopback can be overwritten.
