### ISSUE TITLE
Can this be enabled using middleware.json?

### ISSUE THREAD

**Issue by gausie** [strongloop/loopback-component-passport#69]
Would be nice to see an example!

**Comment by BerkeleyTrue** [comment]
Now it is enabled by default in `session:after` phase in 1.5.0. [here](https://github.com/FreeCodeCamp/freecodecamp/tree/staging/server) is an example I just completed moving over to use phases.

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/loopback-example-passport too.
