### ISSUE TITLE
BUG:passport-configurator.js: defaultCallback has incorrect params for passport.authenticate

### ISSUE THREAD

**Issue by wenwei1202** [strongloop/loopback-component-passport#89]
/lib/passport-configurator.js  
function: defaultCallback  line:423

the third param is a function with params 'req', 'res' which will be called when authentication succeeds, should like below:
```
app.get('/auth/facebook/callback',
  passport.authenticate('facebook', { failureRedirect: '/login' }),
  function(req, res) {
    // Successful authentication, redirect home.
    res.redirect('/');
  });
```
but in defaultCallback:
```
passport.authenticate(name, _.defaults({session: session},options.authOptions), function(err, user, info) {});
```
I think the callback 'function(err, user, info)' doesn't really work

**Comment by kevintechie** [comment]
The loopback-component-passport module uses the Passport custom callback to handle validation. It does this because not all strategies work with the validation handling built in to Passport. Look at the Passport documentation (scroll down to Custom Callback: http://passportjs.org/docs/authenticate

**Comment by wenwei1202** [comment]
I see , thank you @kevintechie. And now I know why loopback-component-passport calls req.login(), I was a little confused about this before.

**Comment by superkhau** [comment]
@wenwei1202 Are you still running into issues? Is this good to close?
