### ISSUE TITLE
Support overriding authorizationURL on request-by-request basis

### ISSUE THREAD

**Issue by mhamann** [strongloop/loopback-component-passport#90]
I have a need in an `openid connect` flow to support a differing authorizationURL based on some information about how the user arrived at my app. I know this is a niche use case, but it would be nice if this module could support it. I can achieve this functionality with the standard `passport` library by simply extending the existing OAuth2.0 strategy with a small bit of extra logic. However, I don't think I can do this with `loopback-component-passport` because I can't control what gets passed to `passport.authenticate`.

I would like to be able to override / control what gets passed through the initial `passport.authenticate` call to initiate an OAuth flow. I think this would likely involve passing a function override during the component's `configure` step.

**Comment by raymondfeng** [comment]
Did you look at https://github.com/strongloop/loopback-component-passport/blob/master/lib/passport-configurator.js#L368?

**Comment by mhamann** [comment]
@raymondfeng thanks for the link. I have seen that, and am using it.

My need is actually here (apologies if that wasn't clear from the original description): https://github.com/strongloop/loopback-component-passport/blob/master/lib/passport-configurator.js#L510-L513

I want to be able to pass in extra properties via the object sent to `passport.authenticate`.
