### ISSUE TITLE
Custom verified function for strategy

### ISSUE THREAD

**Issue by yakimun** [strongloop/loopback-component-passport#92]
How can be overriden the default `verified` function for specific strategy?
`req._passport.instance._strategies['facebook-token']._verify` override does not work.

**Comment by superkhau** [comment]
@raymondfeng ^

Possible feature.

**Comment by benkroeger** [comment]
I am using something very similar in one of my former internal projects. [loopback-component-passport-custom-schemes](https://github.com/benkroeger/loopback-component-passport-custom-schemes) allows to define custom auth schemes along with custom verify functions. **Note:** the referenced repo is not final - for now, I just wanted to have a dump in git. Will continue development / cleanup / documentation in near future
