### ISSUE TITLE
Use passport login (ldap) in rest

### ISSUE THREAD

**Issue by octera** [strongloop/loopback-component-passport#96]
Hi there,
I'm able to login with LDAP, it's pretty awesome.
Now I have to do the same thing with an REST call to the login method.
I don't see how this plugins can integrate with a call rest... Maybe with a hook "beforeRemote"? But I don't know what to put inside the method...

Thanks for your help

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See h    ttps://github.com/strongloop/loopback/wiki/Questions for more details.
