### ISSUE TITLE
API

### ISSUE THREAD

**Issue by mike-aungsan** [strongloop/loopback-component-passport#98]
There are a few issues I would say.

First, it does not show any API in the API explorer. So I don't know how to use / which API to call
Notice that username and passport are post to auth/local

Second,
Provider is "ms-ad". 
searchAttributes are the following.

"searchAttributes": ["name", "employeeID", "mail", "mailNickname", "manager", "jobDescription",  "givenName"],

I do not see any of those information are saved in userIdentity.

I notice that the routes are defined in the providers.json

  {
    ...
    "authPath": "/auth/local",
    "successRedirect": "/auth/account",

```
"failureRedirect": "/msad",
"failureFlash": true,
...
```

  }

I tried with wrong username/email or password. I do not see any error message are set.

I check the code in passport-configurator.js for case 'ldap':
I do not see any error message are set

Any help or any link?

Many Thanks

**Comment by mike-aungsan** [comment]
Can we change or add more property into user at between line 224 and 225?

https://github.com/strongloop/loopback-component-passport/blob/master/lib/passport-configurator.js

if (user) {

            if (!!email) {
              profile.emails = [{value: email}]
            }
            profile.attributes = user
            var OptionsForCreation = _.defaults({
              autoLogin: true
            }, options)
}

**Comment by loay** [comment]
Hi @mike-aungsan 
Thanks for your post. Looking into these issues. In the mean time, did you have a look at the passport example here:
https://github.com/strongloop/loopback-example-passport

**Comment by srinivas-os** [comment]
+1, having the same issues.
